### ISSUE TITLE
Example how to use it.

### ISSUE THREAD

**Issue by filipecosta01** [telegram-bot-rb/telegram-bot#1]
It would be nice to have an example project showing the confs for the bot to work.
I've been trying to setup a new rails project with this library and I could not get it working properly, as I'm new to rails development.

Any help would be appreciated. Thanks.

**Comment by printercu** [comment]
Hi, here i've made one: https://github.com/telegram-bot-rb/telegram_bot_app

There are some basic features are used: sessions and contextual commands. Try to explore separate commits to check evolution of code.

**Comment by filipecosta01** [comment]
Awesome, thanks for the quick response.

Maybe you can include this test bot into this repository readme file. It will help others.

Thanks again, I can close this issue.
