### ISSUE TITLE
Bot API upgrade to version 4.1

### ISSUE THREAD

**Issue by RalfHerzog** [telegram-bot-rb/telegram-bot#100]
At first, thanks for this easy to use gem.
I would like to use bot media message updates ([editMessageMedia](https://core.telegram.org/bots/api#editmessagemedia)) which are available since API version 4.0 but the repo's api version is only at 3.5 . As described in the readme, I ran `bin/fetch-telegram-methods` and saw the new API methods (api_methods.txt):
* sendAnimation
* editMessageMedia
* setPassportDataErrors

For sure, I can do a PR for the three added methods but the tests will be missing. I would appreciate if someone who is familiar with rspec testing could work on that. Thanks!

**Comment by printercu** [comment]
Hi! Thanks for reminding about new api version, I've missed it.

There is no tests for this methods, because they are just aliases. I've just released 0.14.1 with updated methods list.
