### ISSUE TITLE
webhook 404 

### ISSUE THREAD

**Issue by bestony** [telegram-bot-rb/telegram-bot#101]
i try to use 'rails telegram:bot:set_webhook --trace RAILS_ENV=production' to set my bot webhook , and set webhook

Rails Routes Result:
![image](https://user-images.githubusercontent.com/13283837/44996707-f94be780-afdb-11e8-9848-bf03bf51ae4b.png)

Bot Webhook Info Result
![image](https://user-images.githubusercontent.com/13283837/44996723-0e287b00-afdc-11e8-8744-ca4267480724.png)

route code here 
```
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  telegram_webhook TelegramController
end
```

log is here 
```
F, [2018-09-04T00:48:02.056644 #3381] FATAL -- : [a260e569-7a33-42d4-a430-d2db02ce8f84] ActionController::RoutingError (No route matches [POST] "/telegram/585377978_AAHwxxxxxx0_UBj8"):
```

**Comment by kk47042** [comment]
How did you make this work?
