### ISSUE TITLE
How to dispatch inline query in rspec?

### ISSUE THREAD

**Issue by marckohlbrugge** [telegram-bot-rb/telegram-bot#103]
I'm trying to write a rspec test for my inline queries, but can't figure out how to call the inline query from within my tests. Any suggestions?

I'm familiar with helper methods such as `dispatch_message("/command")`, but there doesn't seem to be an equivalent for inline queries.

I think the solution would be something like `dispatch(inline_query: { query: "foobar" } )` but I'm unsure of the exact format.

**Comment by printercu** [comment]
Hi! You're on the right way. Just add any other desired fields along with `query`: https://core.telegram.org/bots/api#inlinequery . There is already simple `from` [implementation](https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/rspec/message_helpers.rb#L4), which can be useful: `dispatch(inline_query: {from: from, query: ...})`.

**Comment by marckohlbrugge** [comment]
Thanks!
