### ISSUE TITLE
Commands with mentions in group chats

### ISSUE THREAD

**Issue by oma84** [telegram-bot-rb/telegram-bot#105]
**Little note**
First of all I'd like to inform, that it seems like the Bot-API (from telegram) has an error according to bots, which have the privacy setting enabled, because a "@botname message" doesn't cause any update. That shouldn't be an error in the gem, but maybe this info helps people, who stumble upon that problem. (Maybe you could add an info to the readme?)

**Actual problem**
If there is more than one bot in a group chat a "/command@botname" could be called to address the correct bot (and is automatically suggested, if one created a command list for the bot). But instead of being processed by the according Controller action / method it is processed by the "message" action / method in the Controller.

Am I doing something wrong? Or was this case just not token into account / implemented yet?

**Comment by printercu** [comment]
Hi! I'll check your first note soon. According to issue, do you set right username for bot? Please see config section in readme for details.

**Comment by oma84** [comment]
Ah, that might do the trick. I just added the token, but not the name! I'll try that! Thanks for your quick reply.

**Comment by oma84** [comment]
Yes, it did the trick. Works like a charm now. And I feel stupid now, because I already stumbled upon those two options, but wasn't able to see the connection to my problem. \*facepalm\*
Thank you very much for your help, the quick response and the gem itself :)

**Comment by printercu** [comment]
Glad to hear :)
According to your first note. Here is telegram docs: https://core.telegram.org/bots#privacy-mode . It does not say that bot should receive messages where it's mentioned. It seems to me that it had been so some day, but then rules changed.

**Comment by printercu** [comment]
I've reread you comment and understand that problem is in getting messages with explicit mentions in group chat (looks like usual messages trigger updates, but with mentions - not).

I've just checked this and see that I poller receive updates for all messages in group chat: plain text, with bot mention, with anyone-else mention.

**Comment by oma84** [comment]
Before I re-read the section about privacy-mode and which messages exactly will be received, I thought that I read something like "messages in group chats, where the bot is mentioned". But you're right: That's written nowhere. The only time is in connection with the command.

Maybe it was never possible and shall never be? I don't know :)

Maybe I only assumed, that if writing "normal" messages to the bot in a one-on-one private chat is possible, that it also must be possible in a group chat with a mention.
