### ISSUE TITLE
Working bot example

### ISSUE THREAD

**Issue by deadalice** [telegram-bot-rb/telegram-bot#108]
I am proud to present a unique working bot where some rare features are realized, such as channel commenting and "interface"-like conversating, instead of popular "flow", powered by this beautiful gem.

Feel free to comment and use my first RoR work and suggest possible improvements. 

I want to thank the author of this gem, who inspired me to study this beautiful platform and create something new. Thank you guys, you influenced at least one person for the better.

My sourse: https://gitlab.com/deadalice/chllng/
Powered by this gem bot: https://t.me/cotdbot
Channel: https://t.me/chllng

**Comment by printercu** [comment]
Hi, and thanks for sharing! I'm really happy that this gem is helpful and powers such apps.

I've added bot to the list of built-with: https://github.com/telegram-bot-rb/telegram-bot/wiki/Bots-built-with-telegram-bot-gem
