### ISSUE TITLE
Message ID from callback_query

### ISSUE THREAD

**Issue by dsounded** [telegram-bot-rb/telegram-bot#111]
Right now it returns only callback_query as a string, will be great to have an ability to have an access to `from` like described here https://stackoverflow.com/questions/48559078/editing-telegram-bot-messages-using-ruby

**Comment by dsounded** [comment]
Seems it's available through `payload['message']['message_id']`

**Comment by printercu** [comment]
Hi! You can find some useful helpers in https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/reply_helpers.rb
Looks like edit_message should work for you.

**Comment by dsounded** [comment]
@printercu yeah, it works, the main problem I wasn't figure out how to retrieve an ID of message related to the button pressed, but eventually I found it through `payload`
