### ISSUE TITLE
Callback queries pass nil as data in callback method

### ISSUE THREAD

**Issue by holywyvern** [telegram-bot-rb/telegram-bot#112]
## Summary

When I test from my local computer a poll of a callback query with a game inside, it passes data as nil on callback_query method.
But when you actually look at the console, it is displaying properly:

### Console output

```
Processing by Telegram::Bots::RexGamesController#callback_query
  Update: {"update_id": [[redacted]],"callback_query":{"id":"[[redacted]]","from":{"id": [[redacted]],"is_bot":false,"first_name":"[[redacted]]","last_name":"[[redacted]]","username":"[[redacted]]","language_code":"[[redacted]]"},"inline_message_id":"[[redacted]]","chat_instance":"[[redacted]]","game_short_name":"[[redacted]]"}}
===
nil
```

### Environment information

- *OS*: Linux Subsystem Ubuntu 16 on Windows 10 (x64)
- *Ruby version*: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
- *Rails version*: 5.2.2
- *Database engine*: Postgresql

### Pre conditions

- You must have a Telegram bot already created
- You must have configured a default bot

- I don't know if this affects the bot somehow, but i used to have it to another webhook, however I removed it using `Telegram.bot.delete_webhook` to allow polling.

### Steps

1. Create a new Telegram Updates Controller:

```rb
  class WebhookController < Telegram::Bot::UpdatesController
      include Telegram::Bot::UpdatesController::TypedUpdate

      def callback_query(data)
        p '==='
        p data
      end
  end
```

2. Start poller using `rake telegram:bot:poller`
3. Perform a callback query for a game

## Expected result

`data` should be an instance of Telegram::Bot::Types::CallbackQuery containing callback query information.

## Current result

`data` is processed as `nil`.

## Notes

`payload` contains the proper object, if you print payload in the controller it is shown as: `#<Telegram::Bot::Types::CallbackQuery:object_id`.

**Comment by printercu** [comment]
Hi! `data` argument passed to this method is actually `data` field from payload, which is passed from button: https://core.telegram.org/bots/api#callbackquery
All this arguments are just shortcuts, which I've found handy for every particular action. Complete object is available with `payload` method in every action, which is `data` you expect.

**Comment by holywyvern** [comment]
Oh thanks, then it's working properly,
