### ISSUE TITLE
Telegram::Bot::Client::AsyncJob ignores 

### ISSUE THREAD

**Issue by marckohlbrugge** [telegram-bot-rb/telegram-bot#116]
When setting `config.active_job.queue_name_prefix = "foobar_"` in `enviroments/production.rb` I expect `Telegram::Bot::Client::AsyncJob` to use a queue named `foobar_default`, however it ignores the prefix and just uses `default`.

Other jobs inheriting from `ApplicationJob`(which defaults to `queue_as :default`) do use the prefix and get queued in `foobar_default` as expected.

It seems like `Telegram::Bot::Client::AsyncJob` dynamically generates a Job class using `ApplicationJob`. I expect something is going wrong there.

https://github.com/telegram-bot-rb/telegram-bot/blob/20427499c3b81c4b4926191d323e7c4f374ce62a/lib/telegram/bot/async.rb#L61,L63

Related `ActiveJob` code: https://github.com/rails/rails/blob/819b06f494d2b934b3124808526debe0aa81b57a/activejob/lib/active_job/queue_name.rb

**Comment by printercu** [comment]
Hi! Is it possible that you access bot before the line `config.active_job.queue_name_prefix=`?

**Comment by marckohlbrugge** [comment]
> Hi! Is it possible that you access bot before the line `config.active_job.queue_name_prefix=`?

I don't have anything in my `production.rb` with regards to Telegram. I do have an initializer with `Telegram.bots_config`, but I don't think that should have an impact.

**Comment by printercu** [comment]
What does `ApplicationJob.queue_name` return? I've just tested in the app and it looks like queue_prefix does not affect jobs until `queue_as` is called. Tested on 5.2.3. I think this is rails issue and can be reported there:

```
# breakpoint in routes.rb inside `.draw` block
[1]> ActiveJob::Base.queue_name_prefix
=> "foobar_"
# ensure that ApplicationJob was not loaded before prefix was set
[2]> Object.const_defined?(:ApplicationJob)
=> false
[3]> ApplicationJob.queue_name
=> "default"
```

Default bot's job is inherited from `ApplicationJob` so it inherits the queue name. Adding `queue_as :default` to `ApplicationJob` fixed the issue.

Closing as it's not related to the gem. Feel free to ping me to reopen.

**Comment by marckohlbrugge** [comment]
Thanks. I did some more reading about this and it might be Sidekiq that's at fault here. The creator discourages the use of queue prefixes, so I think that's what I'm going to do.
