### ISSUE TITLE
answerPreCheckoutQuery

### ISSUE THREAD

**Issue by muhammadn** [telegram-bot-rb/telegram-bot#117]
i saw `answerPreCheckoutQuery`  here:

https://github.com/telegram-bot-rb/telegram-bot/blob/380d13f65a62786f5ccdb8849abd408c58b42766/lib/telegram/bot/client/api_methods.txt#L66

but i don't see any of the code here:

https://github.com/telegram-bot-rb/telegram-bot/blob/20427499c3b81c4b4926191d323e7c4f374ce62a/lib/telegram/bot/updates_controller/reply_helpers.rb

It seems that pre_checkout_query after sendInvoice looks partially implemented and we do need answer_pre_checkout_query to reply to the user to complete the checkout after purchasing on telegram

**Comment by printercu** [comment]
Hi and thanks for the contribution!

BTW, this one was not partially implemented. There might be other methods which miss helpers in controller. To keep api simple, there are helpers only for very basic actions. And at any time you can use `bot.answer_pre_checkout_query(...)` or call any other method you want from controller.

**Comment by printercu** [comment]
released 0.14.2 with new helpers
