### ISSUE TITLE
Stop controller execution

### ISSUE THREAD

**Issue by bibarsov** [telegram-bot-rb/telegram-bot#12]
Hi. I build my bot that contains `before_filter` function that checks if user banned or not. So, I'm stuck with the problem: without extending controller from AbstractController my application won't stop execution in before_filter method. I tried to include ActionView::Helpers::RenderingHelper (f.e. to use `render :nothing => true, :status => 200` ) and other modules,  but none of them works.. How can I do it?

**Comment by printercu** [comment]
Use `throw :abort` in Rails 5 or return `false` in Rails 4. Rails has changed the way of terminating callbacks, so does telegram-bot.

**Comment by printercu** [comment]
If you don't use rails check the version of ActiveSupport.

**Comment by bibarsov** [comment]
Thanks so much, it worked:)
