### ISSUE TITLE
spec: Telegram::Bot::ClientStub.stub_all! seems to not work if  telegram_webhook on an app engine

### ISSUE THREAD

**Issue by caherrerapa** [telegram-bot-rb/telegram-bot#120]
I currently have a rails app which mounts an engine called `MyEngine`
`my_engine/routes.rb`
```
MyEngine::Engine.routes.draw do
  telegram_webhook MyEngine::Telegram::WebhookController
end
```
If I declare this way, when I'm trying to run the `dispatch_message` it doesn't find the `telegram_webhook_path`
```
describe MyEngine::Telegram::WebhookController, telegram_bot: :rails do
end
```
I get `undefined method 'telegram_webhook_path' for #<Module:0x00007fee3059d8e8>'` when I call any dispatch_message on the spec

When I declare `telegram_webhook MyEngine::Telegram::WebhookController` on the main app rather than on the engine, I get the the method `post` is undefined. I would like to still keep separated my engine and its tests but I can't find the way to make the test work without adding the route in the main app `routes.rb`

I'm using Rails 4.2

**Comment by caherrerapa** [comment]
I found out that in Rails 4.2 you need to add `type: :request` to the describe declaration
```
describe MyEngine::Telegram::WebhookController, type: :request, telegram_bot: :rails do
end
```

**Comment by printercu** [comment]
Hi! You can redefine default path helper (https://github.com/telegram-bot-rb/telegram-bot/blob/ca4ea9e6cb859a31df582d7967f9430e18955a5c/lib/telegram/bot/rspec/integration/rails.rb#L6-L9) to whatever value you need:
```ruby
let(:controller_path) { your_engine.routes.telegram_webhook_path }
# or even hardcode it
let(:controller_path) { '/engine/telegram/...' }
```

I don't know how to implement transparent support for rails engines. If you have an idea please propose a PR.
