### ISSUE TITLE
How to use send_poll method ?

### ISSUE THREAD

**Issue by Nmerey** [telegram-bot-rb/telegram-bot#124]
I was trying to send poll via responding with Poll like so:
`respond_with :poll, question: 'some question here?', options: ['yeas','no']`
is it a correct way of using poll ?

**Comment by printercu** [comment]
This should work, I didn't tried this polls yet. Do you get an error? If so, does `respond_with :message, text: 'Hello!'` works?

**Comment by Nmerey** [comment]
Yeah, simple respond_with works.
it gives me error like this:

> undefined method `send_poll' for #<Telegram::Bot::Client#70263694578320(team_sorter)>
Did you mean?  send_photo

**Comment by printercu** [comment]
This method was added to the gem recently and was not released yet. Please try installing the gem from master. I'll release 0.14.3 several hours later.

**Comment by Nmerey** [comment]
Ohh, akey pasibki :*

**Comment by Nmerey** [comment]
Drug, it is working now sending polls and stuff but it is always anonymous I know it is offtop is there any way I can collect user_id from voters ?

**Comment by printercu** [comment]
https://telegram.org/blog/polls it says that this kind of polls are anonymous. Looks like it's only possible to implement polls the same way as `@vote or @poll` do to get responders ids.

**Comment by Nmerey** [comment]
Thanks my man I used ur suggestion and did imitated poll with reply_markups and callback_data!
