### ISSUE TITLE
parse_mode missing for SendMessage method?

### ISSUE THREAD

**Issue by nut707** [telegram-bot-rb/telegram-bot#125]
parse_mode missing for SendMessage method?

I use Telegram Bot to send notifications, do it in rake task, not in controller.
So can not find any way to SendMessage with parse_mode="HTML" option.

**Comment by printercu** [comment]
Does this work?
```ruby
bot.send_message(chat_id: chat_id, text: '<b>Bold</b>', parse_mode: :HTML)
```

**Comment by nut707** [comment]
> Does this work?
> 
> ```ruby
> bot.send_message(chat_id: chat_id, text: '<b>Bold</b>', parse_mode: :HTML)
> ```

Thanks, it works. What did i miss? How i should find out this?

**Comment by printercu** [comment]
From readme:

> There is `request(path_suffix, body)` method to perform any query. And there are shortcuts for all available requests in underscored style (`answer_inline_query(params)` instead of `answerInlineQuery`).

```ruby
bot.request(:getMe) or bot.get_me
bot.request(:getupdates, offset: 1) or bot.get_updates(offset: 1)
bot.send_message(chat_id: chat_id, text: 'Test')
```
> There is no magic, they just pass params as is and set path_suffix.
