### ISSUE TITLE
Use random string for telegram_webhook route

### ISSUE THREAD

**Issue by rguiscard** [telegram-bot-rb/telegram-bot#127]
It currently uses bot secret as part of telegram_webhook route (/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/routes_helper.rb). I wonder whether it is possible to use a user-given random string instead of bot secret. Bot secret should be kept as secret as possible. I understand that https protocol should prevent ear-dropping. But having a random string different from bot secret would be better. Probably just add another argument in telegram_webhook method to make it work.

**Comment by printercu** [comment]
Hi! Sorry for the so late reply and thanks for pointing this out.

At first it was made on the advice from [telegram's website](https://core.telegram.org/bots/faq#how-can-i-make-sure-that-webhook-requests-are-coming-from-telegram). It was simple solution and some of drawbacks were not clear.

No I see that this way have several security flaws: url can be logged on proxies or sent to errors collector, for example. So I've enabled hashing of token for urls by default. And added `:path` option as well.
