### ISSUE TITLE
Detect conversation interuption

### ISSUE THREAD

**Issue by hyzyla** [telegram-bot-rb/telegram-bot#128]
Hi. I have a bot with two steps implemented via context, but when I entering the new command the previous conversation interrupted. How can I implement detecting conversation interruption or prevent interruption at all?

**Comment by printercu** [comment]
Hi! Here is how message context is implemented: https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/message_context.rb#L52
`super` there returns nil only if there is no command in the message.

There are different approaches: override this method and keep value in the session if new command is given, or copy the whole module and tune it. It depends on your requirements.

**Comment by hyzyla** [comment]
Thanks, I think the overriding method will solve my requirements.
