### ISSUE TITLE
ArgumentError: Missing host to link to! after rake telegram:bot:set_webhook 

### ISSUE THREAD

**Issue by denker** [telegram-bot-rb/telegram-bot#13]
Hello,

I try to set webhook on production server, but get 'missing host' error, even though host is set both [production.rb](https://github.com/denker/lifetracker/blob/master/config/environments/production.rb). Same problem appears on dev machine with :host=>'localhost:3000'.

> denker@ubuntu-timzuev:~/deploy/lifetracker/current$ rake telegram:bot:set_webhook RAILS_ENV=production
> rake aborted!
> ArgumentError: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
> /home/denker/deploy/lifetracker/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/url.rb:62:in 'full_url_for'
> /home/denker/deploy/lifetracker/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/url.rb:52:in `url_for'
> /home/denker/deploy/lifetracker/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:303:in `block in <class:RouteSet>'
> /home/denker/deploy/lifetracker/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:175:in `call'
> /home/denker/deploy/lifetracker/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:295:in `block (2 levels) in define_url_helper'
> /home/denker/deploy/lifetracker/shared/bundle/ruby/2.3.0/gems/telegram-bot-0.8.0/lib/tasks/telegram-bot.rake:22:in `block (4 levels) in <top (required)>'
> /home/denker/deploy/lifetracker/shared/bundle/ruby/2.3.0/gems/telegram-bot-0.8.0/lib/tasks/telegram-bot.rake:20:in `each'
> /home/denker/deploy/lifetracker/shared/bundle/ruby/2.3.0/gems/telegram-bot-0.8.0/lib/tasks/telegram-bot.rake:20:in `block (3 levels) in <top (required)>'
> /home/denker/deploy/lifetracker/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
> /home/denker/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
> /home/denker/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
> Tasks: TOP => telegram:bot:set_webhook
> (See full trace by running task with --trace)

**Comment by printercu** [comment]
You need to set host explicitly, 'cause gem can not know what host to use for webhooks.

You can set it with smth like
```ruby
    Rails.application.routes.default_url_options =
      if Rails.env.production?
        {host: 'yourdomain.com', protocol: 'https'}
      else
        {host: 'localhost:3000'}
      end
```

I'll add support for HOST envvar in rake task later.

**Comment by denker** [comment]
Thanks a lot!
