### ISSUE TITLE
Button stays loading

### ISSUE THREAD

**Issue by makdisse** [telegram-bot-rb/telegram-bot#133]
Whenever I answer a callback with reply_with the button that I've used to generate the callback gets a clock icon and stays loading until a timeout happens.

![image](https://user-images.githubusercontent.com/2868648/80405464-8f700800-88ba-11ea-9406-728b348a4c56.png)
 
From the documentation I fail to understand if this 'loading' state is something I must handle or reply_with will

Thanks for the great gem!

**Comment by printercu** [comment]
Hi! This confused me as well for the first time I've faced it. I edited messages as a response to callback queries, and it didn't remove this loading icon from the message. Client also showed errors that callback query timed out.

I found the only solution - use `answer_callback_query` for every single callback query along with any other api request bot performs.

Please let me know if you find a better approach.

**Comment by printercu** [comment]
It looks like now `text` param is optional for answerCallbackQuery request. You can try to use ` answer_callback_query(nil)`. Before it was mandatory and it was hard to decide what to show in alert, because actual reply was within a usual message.
