### ISSUE TITLE
Issue for hash when sending message

### ISSUE THREAD

**Issue by dvodvo** [telegram-bot-rb/telegram-bot#135]
The webhooks are aprticularly useful for identirying a user and storing said user's ID and thus be able to provide notifications, whereby undertaking the action is an opt-in.  To confirm success, a message should be sent. However it is not apparent how the message gets sent.

in the console:
```
    require 'telegram/bot'
    => false
   bot =Telegram::Bot::Client.new('99998210:gibberish') 
   => #<Telegram::Bot::Client#70293339617900()>
   bot.send_message(chat_id: '33999941', text: 'hello there')
   Telegram::Bot::Error (Bad Request: Bad Request: chat not found)
```

which doesn't jive with the [indications of this section](https://github.com/telegram-bot-rb/telegram-bot#client)  .  Further:
```
    bot.request(:get_me)
    Telegram::Bot::NotFound (Not Found)
    bot.get_me
   => {"ok"=>true, "result"=>{"id"=>99998210, "is_bot"=>true, "first_name"=>"my_named_bot", "username"=>"my_named_bot", "can_join_groups"=>true, "can_read_all_group_messages"=>false, "supports_inline_queries"=>false}}
```
So there may be some syntax I am missing/misunderstanding.

How can this be overcome?

**Comment by printercu** [comment]
Hi!

Any unsuccessful request throws exception in the case of failure, so failures are handled as usual with `rescue` section. Successful responses return hash from parsed response json (or response object in typed mode): you can see it  in your second example.  `Telegram::Bot::NotFound` is an exception and will be thrown when running not from console.

`path_suffix` in the readme section is the suffix from the API endpoints. It's named `METHOD_NAME` in this section https://core.telegram.org/bots/api#making-requests
As readme says `.request` is low-level method, and it expects valid suffix which satisfy telegram's API. Helper methods uses snake_case to keep code in usual ruby style.

**Comment by dvodvo** [comment]
Hi!
So of course I had bad syntax putting chat_id as a string rather than an integer.  However
` bot.send_message(chat_id: 33999941, text: 'hello there')` does return `Telegram::Bot::NotFound (Not Found)` in the console, so I do require clarification about the comment: "will be thrown when running not from console"  is it the 'not' that is throwing me off?

**Comment by printercu** [comment]
Try 
```
def example
  bot =Telegram::Bot::Client.new('99998210:gibberish') 
  bot.send_message(chat_id: '33999941', text: 'hello there')
  puts 'After send_message'
end
example
```

You'll see that `After sand_message` is not printed. There is a [tutorial about exceptions](http://rubylearning.com/satishtalim/ruby_exceptions.html).

**Comment by dvodvo** [comment]
The issue was elsewhere: User `id` is the same as `chat_id` which was a source of confusion. If the user closes the chat, Bot cannot send a message to it, thus `NotFound` error. (This *is* the appropriate opt-in/opt-out behaviour)

**Comment by printercu** [comment]
@dvodvo please provide PR if you have idea how to improve gem.
