### ISSUE TITLE
Handling on success

### ISSUE THREAD

**Issue by dvodvo** [telegram-bot-rb/telegram-bot#136]
Hello,

The Telegram API documentation states `On success, the sent Message is returned.`
The readMe provides indications for Error and Forbidden errors.

But what is the proper way to handle the success case, for say `bot.send_message(chat_id: chat_id, text: 'Test')` in case one would want to log/store it?

**Comment by printercu** [comment]
```ruby
result = bot.send_message(chat_id: chat_id, text: 'Test')
log.info(result.to_json)
```
