### ISSUE TITLE
How to make user to force_reply to save_context ?

### ISSUE THREAD

**Issue by Nmerey** [telegram-bot-rb/telegram-bot#138]
Used reply_with and save_context inside callback_query like so:
```
def callback_query(data)
...
    elsif data[0] == 'f'
      session[:venue_id]  = @venue.id
      session[:callback]  = payload["message"]
      session[:friend_id] = from['id']

      reply_with :message, text: "Add Name and Rating\nLike so: Chapa 3", reply_markup: {force_reply: true, selective: true}
      save_context :add_friend
..
end
```
What I basically want is for keyboard go up and make condition to stick as replied_to message.
Any idea?
P.S Thanks @printercu for such a great gem!

**Comment by printercu** [comment]
Hi! `save_context` works the same way with `force_reply`: the next message from user will be handled with `add_friend` method.

If you want to show simple or inline telegram keyboard then it's not compatible with `force_reply`. If you want to change inline keyboard for existing message, then you need to use `editMessage*` method which can change keyboard as well (there is a helper `edit_message`).

If you want the other scenario, please provide an example with sample messages.

**Comment by Nmerey** [comment]
Sorry for not greating you my friend! Peace be upon you!

It actually worked for me when I just did it like
``` 
reply_with :message, text: "Add Rating and Name", reply_markup: {force_reply: true}
save_context :add_friend
```
But the problem was it made all grop members keyboard to go up as a reply mesage.
When I added `selective: true` it did not work as a reply message.

![Снимок экрана 2020-06-16 в 16 49 17](https://user-images.githubusercontent.com/32390632/84782980-5e29d380-aff1-11ea-932b-52b25d54d4f9.png)

**Comment by Nmerey** [comment]
I have noticed something interesting. It works as a I want on local server and does not on heroku.
I will put link to code below.
https://github.com/Nmerey/team_sorter_bot

**Comment by printercu** [comment]
So the problem is not in save_context, but in the way how telegram handles force_reply?

**Comment by Nmerey** [comment]
No I believe it is how puma handles it local and remote.

**Comment by printercu** [comment]
Description for `selective` (https://core.telegram.org/bots/api#forcereply) states:

> Targets: 1) users that are @mentioned in the text of the Message object; 2) if the bot's message is a reply (has reply_to_message_id), sender of the original message.

There is nothing said about callback queries. I think you need to add explicit mentions to the message to make it work as expected.

**Comment by printercu** [comment]
Feel free to ping me to reopen if it's not solved.
