### ISSUE TITLE
rspec photo's sending

### ISSUE THREAD

**Issue by zgfif** [telegram-bot-rb/telegram-bot#139]
I try to write RSpec test to send photo to telegram bot. But there are only **dispatch_message** and **dispatch_command** [helpers](https://github.com/telegram-bot-rb/telegram-bot#testing). Maybe somebody wrote his own helper(for example, **dispatch_photo**), and can take advice on how to perform it? I suppose that mocked photo's request should also be added to the request hash.

**Comment by printercu** [comment]
Hi! There is `Main method is #dispatch(update)` in readme. I think I need to add an example for it. It accepts raw update to dispatch.

However `dispatch_message` should also work: `dispatch_message(text, photo: {....photo_fields...})`

**Comment by zgfif** [comment]
@printercu thank's a lot

**Comment by printercu** [comment]
I've just checked, that files are downloaded with extra `getFile` request. If you need to test file content, I think the only possible option now is to mock the `get_file` for client in a different way like this:

```ruby
before do 
  allow(client).to receive(:get_file).with(file_id) { mocked_response }
end
```

**Comment by printercu** [comment]
Well, and then it requires one more request to download file itself :) I think webmock is the right tool to handle such requests.

**Comment by zgfif** [comment]
I am a newbie in ruby and couldn't find a solution for send_photo in spec.

I use`Telegram::Bot::ClientStub.stub_all!`
```
require 'rails_helper'
require 'telegram/bot/rspec/integration/rails'

RSpec.describe TelegramWebhooksController, telegram_bot: :rails do
  describe '#start!' do
    subject { -> { dispatch_command :start, from: {first_name: 'Pasha'} } }
   it { should respond_with_message 'Hi, Pasha!' }
  end

  describe '#add_tool!' do
    subject { -> { dispatch_command :add_tool } }
    let(:addr) { 'Yaremcha' }
    let(:freq) { '2312' }
    let(:owner) { 'My' }
    let(:new_photo) { File.open('public/ruby_img.png') }

    it 'should ask questions' do
      should respond_with_message I18n.t('tg.add_tool.addr')

      expect { dispatch_message addr }.to respond_with_message I18n.t('tg.add_tool.freq')
      expect { dispatch_message freq }.to respond_with_message I18n.t('tg.add_tool.owner')
      expect { dispatch_message owner }.to respond_with_message I18n.t('tg.add_tool.ask_img')

      expect(Tool.last).to have_attributes(address: addr, frequency: freq.to_i, owner: owner)
      expect(Tool.last.photos.count).to eq(0)
      bot.send_photo(chat_id: chat_id, photo: new_photo)
    end
  end
end

```
I suppose that **bot.send_photo(chat_id: chat_id, photo: new_photo)** should create corresponding request with photo in raw data, but I only see previous performed **dispatch_message owner** :
`#<ActionDispatch::Request:0x000055c1a5b37b00 @env={"rack.version"=>[1, 3], "rack.input"=>#<StringIO:0x000055c1a5c50960>, "rack.errors"=>#<StringIO:0x000055c1a5c50a00>, "rack.multithread"=>true, "rack.multiprocess"=>true, "rack.run_once"=>false, "REQUEST_METHOD"=>"POST", "SERVER_NAME"=>"www.example.com", "SERVER_PORT"=>"80", "QUERY_STRING"=>"", "PATH_INFO"=>"/telegram/849783680_AAHBf0ETLn8L74_mtflyZ8lwXRfqQT2F2kg", "rack.url_scheme"=>"http", "HTTPS"=>"off", "SCRIPT_NAME"=>"", "CONTENT_LENGTH"=>"61", "rack.test"=>true, "REMOTE_ADDR"=>"127.0.0.1", "REQUEST_URI"=>"/telegram/849783680_AAHBf0ETLn8L74_mtflyZ8lwXRfqQT2F2kg", "HTTP_HOST"=>"www.example.com", "CONTENT_TYPE"=>"application/json", "HTTP_ACCEPT"=>"application/json", "HTTP_COOKIE"=>"", "action_dispatch.parameter_filter"=>[:password], "action_dispatch.redirect_filter"=>[], "action_dispatch.secret_key_base"=>"9b6c6fe401db6ca93ea8464ca0f88056f16d3f98944cb38cb7bce52b49d865e1f2601b3b06d0f97bb1f4dc9c27fb78d38bb21731c9ed803a40d94d39d4593b68", "action_dispatch.show_exceptions"=>false, "action_dispatch.show_detailed_exceptions"=>true, "action_dispatch.logger"=>#<ActiveSupport::Logger:0x000055c1a5959a40 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x000055c1a5960a98 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x000055c1a59599f0 @datetime_format=nil, @thread_key="activesupport_tagged_logging_tags:12820">, @logdev=#<Logger::LogDevice:0x000055c1a5960a48 @shift_period_suffix="%Y%m%d", @shift_size=1048576, @shift_age=0, @filename="/home/pasha/projects/ndp/log/test.log", @dev=#<File:/home/pasha/projects/ndp/log/test.log>, @binmode=false, @mon_data=#<Monitor:0x000055c1a59609f8>, @mon_data_owner_object_id=8880>>, "action_dispatch.backtrace_cleaner"=>#<Rails::BacktraceCleaner:0x000055c1a73dc200 @silencers=[#<Proc:0x000055c1a73cfdc0 /home/pasha/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/backtrace_cleaner.rb:100>, #<Proc:0x000055c1a73cfd70 /home/pasha/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/backtrace_cleaner.rb:104>, #<Proc:0x000055c1a73cfbb8 /home/pasha/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.1/lib/rails/backtrace_cleaner.rb:19>], @filters=[#<Proc:0x000055c1a73cfe10 /home/pasha/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/backtrace_cleaner.rb:96>, #<Proc:0x000055c1a73cfc80 /home/pasha/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.1/lib/rails/backtrace_cleaner.rb:16>, #<Proc:0x000055c1a73cfc30 /home/pasha/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.1/lib/rails/backtrace_cleaner.rb:17>, #<Proc:0x000055c1a73cfbe0 /home/pasha/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.1/lib/rails/backtrace_cleaner.rb:18>], @root="/home/pasha/projects/ndp/">, "action_dispatch.key_generator"=>#<ActiveSupport::CachingKeyGenerator:0x000055c1a5e1a5e8 @key_generator=#<ActiveSupport::KeyGenerator:0x000055c1a5e1a610 @secret="9b6c6fe401db6ca93ea8464ca0f88056f16d3f98944cb38cb7bce52b49d865e1f2601b3b06d0f97bb1f4dc9c27fb78d38bb21731c9ed803a40d94d39d4593b68", @iterations=1000>, @cache_keys=#<Concurrent::Map:0x000055c1a5e1a598 entries=2 default_proc=nil>>, "action_dispatch.http_auth_salt"=>"http authentication", "action_dispatch.signed_cookie_salt"=>"signed cookie", "action_dispatch.encrypted_cookie_salt"=>"encrypted cookie", "action_dispatch.encrypted_signed_cookie_salt"=>"signed encrypted cookie", "action_dispatch.authenticated_encrypted_cookie_salt"=>"authenticated encrypted cookie", "action_dispatch.use_authenticated_cookie_encryption"=>true, "action_dispatch.encrypted_cookie_cipher"=>nil, "action_dispatch.signed_cookie_digest"=>nil, "action_dispatch.cookies_serializer"=>nil, "action_dispatch.cookies_digest"=>nil, "action_dispatch.cookies_rotations"=>#<ActiveSupport::Messages::RotationConfiguration:0x000055c1a502de08 @signed=[], @encrypted=[]>, "action_dispatch.use_cookies_with_metadata"=>true, "action_dispatch.content_security_policy"=>nil, "action_dispatch.content_security_policy_report_only"=>false, "action_dispatch.content_security_policy_nonce_generator"=>nil, "action_dispatch.content_security_policy_nonce_directives"=>nil, "action_dispatch.routes"=>#<ActionDispatch::Routing::RouteSet:0x000055c1a5aec358>, "ROUTES_8500_SCRIPT_NAME"=>"", "ORIGINAL_FULLPATH"=>"/telegram/849783680_AAHBf0ETLn8L74_mtflyZ8lwXRfqQT2F2kg", "ORIGINAL_SCRIPT_NAME"=>"", "action_dispatch.request_id"=>"e88bc4f0-ee67-4d99-bec3-3ad12122048b", "action_dispatch.remote_ip"=>#<ActionDispatch::RemoteIp::GetIp:0x000055c1a5c3d658 @req=#<ActionDispatch::Request:0x000055c1a5c3d6a8 @env={...}, @filtered_parameters=nil, @filtered_env=nil, @filtered_path=nil, @protocol=nil, @port=nil, @method=nil, @request_method=nil, @remote_ip=nil, @original_fullpath=nil, @fullpath=nil, @ip=nil>, @check_ip=true, @proxies=[#<IPAddr: IPv4:127.0.0.1/255.255.255.255>, #<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0001/ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff>, #<IPAddr: IPv6:fc00:0000:0000:0000:0000:0000:0000:0000/fe00:0000:0000:0000:0000:0000:0000:0000>, #<IPAddr: IPv4:10.0.0.0/255.0.0.0>, #<IPAddr: IPv4:172.16.0.0/255.240.0.0>, #<IPAddr: IPv4:192.168.0.0/255.255.0.0>], @ip="127.0.0.1">, "action_dispatch.request.path_parameters"=>{}, "action_dispatch.request.content_type"=>#<Mime::Type:0x000055c1a60f77c0 @synonyms=["text/x-json", "application/jsonrequest"], @symbol=:json, @string="application/json", @hash=-2855193831226832792>, "RAW_POST_DATA"=>"{\"message\":{\"from\":{\"id\":123},\"chat\":{\"id\":456},\"text\":\"My\"}}", "action_dispatch.request.request_parameters"=>{"message"=>{"from"=>{"id"=>123}, "chat"=>{"id"=>456}, "text"=>"My"}}}, @filtered_parameters=nil, @filtered_env=nil, @filtered_path=nil, @protocol=nil, @port=nil, @method=nil, @request_method=nil, @remote_ip=nil, @original_fullpath=nil, @fullpath=nil, @ip=nil>
`
maybe, there is another way to check that request in spec?

**Comment by printercu** [comment]
What is the object from raw data, where did you get it?

`bot.send_photo` is the method to send photo to telegram api on bot's behalf. Most likely you need to call it from the controller in the response to user's interaction.

If you want to test an update when bot receives a photo, then use
```ruby
dispatch({message: {photo: [
  {file_id: 123, file_size: 456},
]})
```

**Comment by zgfif** [comment]
Thank you very much!
