### ISSUE TITLE
Setting up session in file_store mode

### ISSUE THREAD

**Issue by dvodvo** [telegram-bot-rb/telegram-bot#140]
Webhook communications, probably after creating non telegram-related controllers and actions (I say 'probably' as I have no certainty given other balls were thrown up in the air in the meantime), stopped being handled.

```
Started POST "/telegram/{bot_id}_{token}" for {telegram_owned_ip} at 2020-06-22 05:45:24 +0000
Cannot render console from {telegram_owned_ip}! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

RuntimeError (session_store is not configured):
```

Given the context of a single-server deployment without heavy incoming traffic, I attempted to set that up

```
class TelegramWebhooksController < Telegram::Bot::UpdatesController
  include Telegram::Bot::UpdatesController::MessageContext

  self.session_store = :file_store
```
but the application will not start as `wrong number of arguments (given 0, expected 1..2) (ArgumentError) [...] activesupport-5.2.4.3/lib/active_support/cache/file_store.rb:24`
and justifiably as that line requires one or two arguments `def initialize(cache_path, options = nil)`. Thus I am having a hard time understanding the [instruction block regarding session](https://github.com/telegram-bot-rb/telegram-bot#session) set-up.  The two options are not clearly distinguished, and `:file_store` needs some arguments.

**Comment by printercu** [comment]
Hi! FileStore requires an argument - filename to store data in. It's not clear from the rails docs, I've find it in a single place: https://api.rubyonrails.org/classes/ActiveSupport/Cache.html#method-c-lookup_store but I think it can be found in http://guides.rubyonrails.org/ or in StackOverflow/Google. Sample application also has example of file_store: https://github.com/telegram-bot-rb/telegram_bot_app/blob/master/config/environments/production.rb

Do you start poller in a rails app? It does not start automatically.

**Comment by dvodvo** [comment]
Hi!  I do launch ` rake telegram:bot:set_webhook RAILS_ENV=[...]`.  The application, still in development has its own cert and https address so the hookup runs.  I assume it's a one-off thing (Telegram stores the https address?), but I do renew the task every so often, uncertain of its necessity.

**Comment by dvodvo** [comment]
```
  config.telegram_updates_controller.session_store = :file_store,
    Rails.root.join('tmp', 'session_store')

```
and removing `self.session_store = :file_store` from the TelegramWebhooksController allowed the server to start.  webhooks flowing.

**Comment by xtsidx** [comment]
In standalone app i use


```
class WebhooksController < Telegram::Bot::UpdatesController
  use_session!
  self.session_store = :file_store, 'tmp/session_store'
```
