### ISSUE TITLE
Could you please make the wiki editable for every user?

### ISSUE THREAD

**Issue by roschaefer** [telegram-bot-rb/telegram-bot#143]
Instructions: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis

I was confused how to delete webhooks and looked into source. It would be nice to:
a) Update documentation how to delete webhooks manually
b) or create a rake task `telegram:bot:delete_webhook`

Option a) sounds more cautious to me, so I tried to find instructions how to setup and teardown webhooks and found this: https://github.com/telegram-bot-rb/telegram-bot/wiki/Deployment

![Screenshot - 2020-10-18T143627 534](https://user-images.githubusercontent.com/2110676/96367645-6173ce00-114f-11eb-982b-f1127ec4e964.png)

Unfortunately I don't see a "Edit" button on the Wiki. Why don't you give permissions to edit the wiki in the first place?

I would add the following:

```suggestion
+### Delete webhook
+
+- Simply run `bot.delete_webhook` for each bot (e.g. `Telegram.bots.map { |_, bot| bot.delete_webhook }`)
+
```

**Comment by printercu** [comment]
Hi! Does it mean that everybody will be able to edit wiki without any review?

Regarding the `delete_webhook` method. There is a note in [the client section of readme](https://github.com/telegram-bot-rb/telegram-bot#client):

> ... there are shortcuts for all available requests in underscored style (`answer_inline_query(params)` instead of `answerInlineQuery`)

I think it should resolve the question about the `delete_webhook`.

Could you please share the use case where it's required to delete a webhook? I hope it's better to keep wiki concise and avoid describing uncommon cases.

**Comment by roschaefer** [comment]
> Hi! Does it mean that everybody will be able to edit wiki without any review?

I would assume there is a review procedure, but I'm not 100% sure as I don't use for other projects. But what's a wiki if it's not publicly editable, after all? You could also just use multiple markdown files in other locations and link to them from the `README.md` (by the way that's how I do it for my repos). Then you have the same review process as for the rest of the code. It's also easily editable with the :pencil2: icon in the top right.

> Could you please share the use case where it's required to delete a webhook? I hope it's better to keep wiki concise and avoid describing uncommon cases.

The use case is that you want to use telegram bot poller in development and you get an error message that you cannot use polling if there are webhooks in place. How to delete the webhook again?


> Regarding the `delete_webhook` method. There is a note in [the client section of readme](https://github.com/telegram-bot-rb/telegram-bot#client):

Well, I can only speak for myself but that would not have helped me to understand this option exists. If I Ctrl+F "delete" (my intuition) there is no search result on the `README.md`.

**Comment by printercu** [comment]
I remember I faced that error when was playing with new features. Does it suggest to `deleteWebhook`? (Later I never used same token for prod and dev anymore, because it's easy to create extra bot dedicated to development).

> If I Ctrl+F "delete" (my intuition) there is no search result on the README.md

There are 70+ api methods, I don't think it's good idea to list them all in readme. They are already available in telegram's docs. Anyway, there is another option `bot.request(:deleteWebhook)`.

**Comment by roschaefer** [comment]
> I remember I faced that error when was playing with new features. Does it suggest to `deleteWebhook`? (Later I never used same token for prod and dev anymore, because it's easy to create extra bot dedicated to development).

Here's the error:
```
Telegram::Bot::Error: Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
````

> There are 70+ api methods, I don't think it's good idea to list them all in readme. They are already available in telegram's docs. Anyway, there is another option `bot.request(:deleteWebhook)`.

No, I tried to explain what my first intuition was. I mean, the next idea was to put "delete" into "Search this repository" and that's how I found it. I'm also not super intent to have the wiki changed, just thought: Hey, either a rake task or at least some documentation could have helped me, let's make life easier for future developers and improve it.

Feel free to close this issue.
