### ISSUE TITLE
Process caption as command?

### ISSUE THREAD

**Issue by marckohlbrugge** [telegram-bot-rb/telegram-bot#144]
My bot users occasionally type a command (such as `/todo`) as part of a caption when uploading an image.

What's the best way to process these kind of commands?

I know I can check for incoming image uploads with a generic `message` action and checking for the presence of a `payload["photo"]`. I also know I can get the caption with something like `payload["photo"].first["caption"]` (haven't confirmed this specific code, but easy enough to figure out).

However, I'm not quite sure how to then process that raw text (e.g. `"/todo buy milk"`) such that it calls the `todo!` action with `"buy milk" ` as the parameter. Similarly to what would happen if someone were to just send the message `/todo buy milk` without any image uploads.

I think the answer lies within the `process` method in `Telegram::Bot::UpdatesController` but I haven't been able to figure out the exact approach.

Any suggestions? How can I parse a string like `"/todo buy milk"` to get the action name (`todo`) and its parameters (`"buy milk"`)?

**Comment by marckohlbrugge** [comment]
Oh, looks like `Telegram::Bot::UpdatesController::Commands.command_from_text` might do what I need!

**Comment by printercu** [comment]
Hi! I think the most proper way is to overwrite `action_for_message` to use caption as well. Something like this
```ruby
def action_for_message
  cmd, args = Commands.command_from_text(payload['text'] || payload['caption'], bot_username)
  return unless cmd
  [[action_for_command(cmd), type: :command, command: cmd], args]
end

alias_method :action_for_channel_post, :action_for_message
```
Looks like `caption` and `text` can not be present at the same time. Otherwise it will be slightly different.

**Comment by marckohlbrugge** [comment]
@printercu wow this is even better than what I had in mind. Thank you for sharing this.

For anyone else who's interested in doing something similar, I recommend creating this helper method as well:

```ruby
def text
  payload['text'] || payload['caption']
end
```

That way you can just refer to `text` in your actions without having to worry whether it was a caption or not.
