### ISSUE TITLE
Support /start@fooBot command format

### ISSUE THREAD

**Issue by betzerra** [telegram-bot-rb/telegram-bot#145]
From [Telegram's Bot page](https://core.telegram.org/bots):
> If multiple bots are in a group, it is possible to add bot usernames to commands in order to avoid confusion:
> ```
>/start@TriviaBot
>/start@ApocalypseBot
> ```
> This is done automatically when commands are selected via the list of suggestions. Please remember that your bot needs to be able to process commands that are followed by its username.

Is there a way to handle these automatically?
It seems that `def start!(data = nil, *)` only handles `/start` and not `/start@fooBot`

**Comment by printercu** [comment]
Hi! There is `username` option for a bot, or if you use Rails see this section https://github.com/telegram-bot-rb/telegram-bot#configuration-in-rails-app

**Comment by betzerra** [comment]
For some reason I'm not able to run the bot with credentials (maybe I'm having same issue as https://github.com/telegram-bot-rb/telegram-bot/issues/74 )

so my workaround was adding this code at `initializers/telegram.rb`

```
require 'telegram/bot'

Telegram.bots_config = {
  default: ENV['TELEGRAM_TOKEN']
}
```

Is there a way to set a username in that method?

**Comment by betzerra** [comment]
Ok, this works:

```
Telegram.bots_config = {
  default: {
    token: ENV['TELEGRAM_TOKEN'],
    username: ENV['TELEGRAM_USERNAME']
  }
}
```
