### ISSUE TITLE
Let's update to rails 6.1

### ISSUE THREAD

**Issue by DalfDev** [telegram-bot-rb/telegram-bot#149]
Hello,

Rails 6.1 are released and I can't update my rails version cause of telegram-bot gem.

```
    telegram-bot was resolved to 0.15.0, which depends on
      actionpack (>= 4.0, < 6.1)
```

Could you help me ?

Have a nice day,

**Comment by Evshved** [comment]
Great idea!

**Comment by printercu** [comment]
Hi! Pleas try `gem 'telebram-bot', github: 'telegram-bot-rb/telegram-bot', branch: 'rails-61'` and let me know if everything works.

**Comment by s-anches** [comment]
> Hi! Pleas try `gem 'telebram-bot', github: 'telegram-bot-rb/telegram-bot', branch: 'rails-61'` and let me know if everything works.

`gem 'telegram-bot', github: 'telegram-bot-rb/telegram-bot', branch: 'rails-61'`

**Comment by DalfDev** [comment]
> > Hi! Pleas try `gem 'telebram-bot', github: 'telegram-bot-rb/telegram-bot', branch: 'rails-61'` and let me know if everything works.
> 
> `gem 'telegram-bot', github: 'telegram-bot-rb/telegram-bot', branch: 'rails-61'`

I will try this tomorrow 

Have a nice day

**Comment by DalfDev** [comment]
It's OK ;)
