### ISSUE TITLE
Save context outside from the controller

### ISSUE THREAD

**Issue by bibarsov** [telegram-bot-rb/telegram-bot#15]
Hi again, I'm trying to call action without update from my ActiveJob, something like:

```ruby
def perform(*args)
  bot = Telegram::Bot::Client.new("#{BOT_API}", "#{BOT_USERNAME")
  controller = SomeController.new(bot, from: "#{user.tg_id}", chat: "#{user.tg_id}")
  controller.process(:test, "blabla")
end
```
And my action looks like:
```ruby
def test(message=nil, *)
  save_context :test
  respond_with :message, text: message
end
```
But save_context won't work. I tried to debug `session` in that place, so I get 
`#<Telegram::Bot::UpdatesController::Session::SessionHash:0x2495690 not yet loaded>`
What can I do in this situation?

**Comment by printercu** [comment]
Please check out https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/session.rb

`#session` will remain not loaded, till it is accessed. You can perform `#load!` or  maybe `#to_h`, so it gets loaded. But I suggest to check that result of `#session_key` is same in all the cases where do you need session.

If it doesn't help, provide this values and what session store do you use.

**Comment by bibarsov** [comment]
Yes, `session_key` is pretty much the same, and I get correct values when I type `session_key`
After some juggling with these commands, for example:
![image](https://cloud.githubusercontent.com/assets/4425630/18227191/e12fb95c-7224-11e6-94bb-43b8b4d53ead.png)
I use store by default - `Rails.application.config.session_store :cookie_store, key: '_some_key'`

**Comment by printercu** [comment]
Please check out readme about session store for bot, it's differs from action-controller's store. Because it could not use cookies.

Do you have working context for usual messages (outside of jobs)?

**Comment by bibarsov** [comment]
I checked out a few times, I just thought you already have useful piece of code or some examples in which may be easy to connect to store and change user's context value.
Well, I tried with `:redis-store`, now it works, thanks!
