### ISSUE TITLE
Telegram::Bot::NotFound

### ISSUE THREAD

**Issue by KonstantinReido** [telegram-bot-rb/telegram-bot#151]
Do I miss something or before `Telegram.bots[:incorrent_bot_username]` used to throw exception `Telegram::Bot::NotFound`? Now I see that with incorrect user name `Telegram.bots` returns `nil`.

**Comment by printercu** [comment]
I remember that `NotFound` has been always used only for HTTP errors. There is [`Telegram::Bot::Client.wrap`](https://github.com/telegram-bot-rb/telegram-bot/blob/8cd948a544b90a984518f4d80a32500f0f037545/lib/telegram/bot/client.rb#L22) which raises error, or Hash's fetch method: `Telegram.bots.fetch(id)`.

**Comment by KonstantinReido** [comment]
@printercu thanks for your answer, I realized why thought that `Telegram.bots` throw exception. Before I did some experiment with incorrect token and most likely because of it saw exception.
