### ISSUE TITLE
Add Ruby 3.0 support

### ISSUE THREAD

**Issue by natsumi** [telegram-bot-rb/telegram-bot#152]
Unable to install this gem under Ruby 3.0

```
ERROR:  Error installing telegram-bot:
        telegram-bot-0.15.1 requires Ruby version ~> 2.0. The current ruby version is 3.0.0.0.
```

Would be nice to have Ruby 3.0 support.

**Comment by printercu** [comment]
Hi! Could you please give it a try:
`gem 'telebram-bot', github: 'telegram-bot-rb/telegram-bot', branch: 'ruby-3.0'`

**Comment by benone** [comment]
> Hi! Could you please give it a try:
> `gem 'telebram-bot', github: 'telegram-bot-rb/telegram-bot', branch: 'ruby-3.0'`

Thanks!

p.s. typo: tele**g**ram :)

**Comment by natsumi** [comment]
@printercu I updated my project to Ruby 3 and the updated telegram-bot.  Everything worked perfectly for me.

Thanks for the quick turnaround.

**Comment by printercu** [comment]
Thanks for checking it out. Just release 0.15.2 with ruby3 support.
