### ISSUE TITLE
Please add an example how to delete message

### ISSUE THREAD

**Issue by yuri-karpovich** [telegram-bot-rb/telegram-bot#154]
Telegram API allows to delete messages from chat (not only own messages). Could you please add an example how to do it with your app?

https://core.telegram.org/bots/api#deletemessage

**Comment by yuri-karpovich** [comment]
Sorry, I didn't noticed an ability to send any request like this:

`self.bot.request(:deleteMessage, chat_id: payload['chat']['id'], message_id: payload['message_id'])`

**Comment by printercu** [comment]
There should be bot.delete_message as well
