### ISSUE TITLE
How to use request_contact

### ISSUE THREAD

**Issue by AlexanderVak** [telegram-bot-rb/telegram-bot#159]
Hi,  I've got an question how correctly use request_contact. I added this field but don't see any results

**Comment by printercu** [comment]
Hey! Try
```
      respond_with :message, text: 'message', reply_markup: {
        keyboard: [text: 'button', request_contact: true],
        resize_keyboard: true,
        one_time_keyboard: true,
        selective: true,
      }
```

**Comment by AlexanderVak** [comment]
Thanks for the answer, I figured it out on my own, but now I've got another problem. I need to store the phone number, and I cant do it. I try to catch it like this: `message.dig('contact')`. But its nil

**Comment by printercu** [comment]
Please share code that you use to send a keyboard and handle message. Do you use it in private or group chats?
