### ISSUE TITLE
Updates Poller error in Rails 5

### ISSUE THREAD

**Issue by arpit** [telegram-bot-rb/telegram-bot#16]
I am getting the following error when trying to run the poller (rails 5)

```
wrong number of arguments (given 2, expected 3)
/Users/arpit/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:258:in `dispatch'
/Users/arpit/.rvm/gems/ruby-2.3.0/gems/telegram-bot-0.8.0/lib/telegram/bot/updates_poller.rb:49:in `block in start'
/Users/arpit/.rvm/gems/ruby-2.3.0/gems/telegram-bot-0.8.0/lib/telegram/bot/updates_poller.rb:72:in `block (2 levels) in fetch_updates'
/Users/arpit/.rvm/gems/ruby-2.3.0/gems/telegram-bot-0.8.0/lib/telegram/bot/updates_poller.rb:70:in `each'
...
```

This looks like because of an API change in the metal.rb class in Rails 5 where the signature changed from 2 to 3 arguments

```
    def dispatch(name, request, response) #:nodoc:
      set_request!(request)
      set_response!(response)
      process(name)
      request.commit_flash
      to_a
    end

```

https://github.com/rails/rails/blob/5-0-stable/actionpack/lib/action_controller/metal.rb

Not sure if this is a known issue and there is a workaround ?

**Comment by arpit** [comment]
Ok, got it to work. The changes I had to make are in this commit:

https://github.com/arpit/telegram-bot/commit/45bb335b7663d787790c9699ecba2a01131e626c

The problem is that Rails 5  changed the signature of the dispatch() method in controllers and now uses instances of ActionDispatch Request and Response. Also the initialize method now needs 3 arguments based on this change.

I am not a rails dev but I'll show it to a few devs and see what the best way to handle this is, and then try to submit a pull request (your feedback is welcome / sought).

**Comment by printercu** [comment]
Thanks for report, I'll take a look closely. It looks little strange, 'cause telegram's controller doesn't use ActionController or Metal but only AbstractController.

**Comment by printercu** [comment]
@arpit I can't reproduce it in https://github.com/telegram-bot-rb/telegram_bot_app (there is rails5 branch). If you would to try with latest rails, please comment out `debbie` from Gemfile.

Don't you use any ActionDispatch modules in your controller?

**Comment by arpit** [comment]
Heh, I think I missed the Rails 5 branch. Will test it with that. 
I am creating an Rails 5 API only project, so not sure if that means anything. 
Will report back on results using the Rails 5 branch

**Comment by arpit** [comment]
Oh and another thing. When I tried deploying to Heroku with my changes, they broke there. In prod environment with webhooks enabled, the `message` method was called with a Hash. But not when the poller was used to call dispatch.

https://github.com/arpit/telegram-bot/commit/fef190aec9c6de0176e399c6199c49cba7fda229

**Comment by printercu** [comment]
Do you have public repo with controller you have problems in? Or can you please create gist with your controller? I think you can omit instance methods.

**Comment by arpit** [comment]
This is so bizarre. So it seems to be fine in a vanilla Rails5 API project (created a repo here: https://github.com/arpit/HelloTelegram) 
Must have been some weirdness in my other app. I am going to close the issue until I can reproduce it.

**Comment by arusa** [comment]
JFI: That problem occurs if you inherit your telegram-class from ApplicationController instead of Telegram::Bot::UpdatesController
