### ISSUE TITLE
Uploading multiple photos

### ISSUE THREAD

**Issue by VanyaNeytrino** [telegram-bot-rb/telegram-bot#161]
Hi, how can I save photos if a user has sent more than one photo? I throw 3 photos into the bot and there is only one photo in the payload. Why is this the case and how can I access the rest of the photos? 
<img width="1029" alt="Screenshot 2021-06-12 at 14 39 11" src="https://user-images.githubusercontent.com/16643839/121774875-21090a80-cb8d-11eb-9bb7-01e63b7435fc.png">

**Comment by printercu** [comment]
Hi! Don't bot receive other photos in the separate payloads?

**Comment by printercu** [comment]
I don't think this is related to this gem and more of a bot API question. StackOverflow can be a better option to look for an answer. Here is what I could find: https://stackoverflow.com/questions/50180048/telegram-api-get-all-uploaded-photos-by-media-group-id and there are more related topics in google
