### ISSUE TITLE
Testing sent messages from any controller (in RSpec)

### ISSUE THREAD

**Issue by rjunior273** [telegram-bot-rb/telegram-bot#169]
My bot just sends messages (like notifications) from many controllers inside my application. When a notification is needed inside a controller action, I just call send_message(...) async and that's it. No need for webhooks or any incoming request to my bot.

How do I test the sent messages from within my controllers (or system) specs? It seems all the testing examples are supposed to be run from inside the webhook controller spec, not from any other controller. Docs says "Instead of performing API requests it stores them in a requests hash."

Is there a way to do that? Something like that, for example:

```
RSpec.describe "Users", :type => :request do
  let(:bot) { Telegram.bot }

  it "notifies when a new user is created" do
    post "/users", ...

    expect(response).to redirect_to(...)
    expect(bot).to send_telegram_message(bot, I18n.t('bot.user_created'), some: :option)
  end
end
```

**Comment by printercu** [comment]
Hey! Yep, you're doing it right. All you need is to include matchers and make sure to enable testing mode:

```ruby
# environments/test.rb
Telegram.reset_bots
Telegram::Bot::ClientStub.stub_all!

RSpec.describe "Users", :type => :request do
  include Telegram::Bot::RSpec::ClientMatchers

  let(:bot) { Telegram.bot }
  after { Telegram.bot.reset }

  it "notifies when a new user is created" do
    post "/users", ...

    expect(response).to redirect_to(...)
    expect(bot).to send_telegram_message(bot, I18n.t('bot.user_created'), some: :option)
  end
end
```

**Comment by rjunior273** [comment]
Thanks for the reply!

Did a quick test with it, but got the following exception:

```
Failure/Error: expect(bot).to send_telegram_message(bot, 'hello', chat_id: chat_id)
     
     ArgumentError:
       matcher only supports block expectations
```
Am I not supposed to pass only "bot" to expect?

**Comment by printercu** [comment]
It needs to wrap the code that performs bot api requests similar to `.change` matcher:

```ruby
expect { post "/users", ... }.to send_telegram_message(bot, I18n.t('bot.user_created'), some: :option)
expect(response).to redirect_to(...)
```

**Comment by rjunior273** [comment]
Nice! Got it working now. Sorry for opening an "issue" for something like a simple question. Didn't find an example anywhere, so been wondering if that was even possible.
Thanks for the help and the gem!
