### ISSUE TITLE
Rescue_from in Controller

### ISSUE THREAD

**Issue by prtngn** [telegram-bot-rb/telegram-bot#170]
Hello and thank you for this awesome gem.
I have one question. How I can use rescue_from in TelegramWebhooksController?

Example:
```
rescue_from 'Error' do |exception|
  puts 'Some error'
end

  def start!(*params)
    @user = User.find(params.first)
    if @user
      ...
    else
      raise 'Error'
    end

  end
```

**Comment by printercu** [comment]
Hi! Here are examples: https://api.rubyonrails.org/classes/ActiveSupport/Rescuable/ClassMethods.html#method-i-rescue_from

Your example does not work, because there is no such class `Error`:
```
[2] pry(main)> Error
NameError: uninitialized constant Error
```

**Comment by prtngn** [comment]
Thanks. With error class working good.
