### ISSUE TITLE
Custom SSL root certificate

### ISSUE THREAD

**Issue by prtngn** [telegram-bot-rb/telegram-bot#171]
Hello. I have a problem. In our organization we have uplink proxy server with our self-signed certificate.
```
rake telegram:bot:poller
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
```
In HTTPClient gem we have this code: https://github.com/nahi/httpclient/blob/4658227a46f7caa633ef8036f073bbd1f0a955a2/lib/httpclient/ssl_config.rb#L54

So, when i add ENV variable SSL_CERT_FILE with our root certificate after first initialize HTTPClient we have this:
```
@_httpclient_cert_store_items=["/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", "/opt/telegram-bot-staging/shared/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/cacert.pem"]>
```
And this is not working.

If I delete standart cacert.pem from _httpclient_cert_store_items all working fine. Or if i add our certificate by hand:
```
client.ssl_config.add_trust_ca("/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem")
```

How I can change initialize @client and first remove all certificates:
```
client.ssl_config.clear_cert_store
```
and after add our certificate?

Help please )

P.S.
In this case
```
@_httpclient_cert_store_items=["/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", "/opt/telegram-bot-staging/shared/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/cacert.pem"]>
```
no working, but this case:
```
@_httpclient_cert_store_items=["/opt/telegram-bot-staging/shared/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/cacert.pem", "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"]>
```
working good.

P.P.S.
tls-ca-bundle.pem have our self-signed root certificate.

**Comment by printercu** [comment]
Hey!

Does `bot.instance_variable_get(:@client).ssl_config.clear_cert_store` work?

**Comment by prtngn** [comment]
So, I add this code:
```
Telegram.bot.client.ssl_config.clear_cert_store
Telegram.bot.client.ssl_config.set_trust_ca '/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem'
```
to config/initializers/telegram.rb

and it working.
