### ISSUE TITLE
Connection to telegram server mishandling certificate leading to mistaken 'expired' conclusion

### ISSUE THREAD

**Issue by dvodvo** [telegram-bot-rb/telegram-bot#178]
`bundle exec rake telegram:bot:set_webhook RAILS_ENV=development` will fail with gem version 0.15.4, rails 6.1.3.2, ruby 2.6.1

In examining the stack trace, there are two obvious break points to examine and get object information, the first in each of these blocks:
```
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:103:in `ssl_connect'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:41:in `initialize'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:26:in `new'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:26:in `create_socket'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/telegram/bot/client.rb:82:in `http_request'

/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/telegram/bot/client.rb:73:in `request'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/telegram/bot/async.rb:151:in `request'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/telegram/bot/client/api_helper.rb:22:in `block (2 levels) in define_helpers'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/telegram/bot/tasks.rb:16:in `block in set_webhook'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/telegram/bot/tasks.rb:55:in `block (2 levels) in each_bot'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/telegram/bot/async.rb:138:in `async'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/telegram/bot/tasks.rb:55:in `block in each_bot'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/telegram/bot/tasks.rb:55:in `each'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/telegram/bot/tasks.rb:55:in `each_bot'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/telegram/bot/tasks.rb:12:in `set_webhook'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/telegram-bot-0.15.4/lib/tasks/telegram-bot.rake:17:in `block (3 levels) in <main>'
/home/deploy/the_app/shared/bundle/ruby/2.6.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/deploy/.rbenv/versions/2.6.1/bin/bundle:23:in `load'
/home/deploy/.rbenv/versions/2.6.1/bin/bundle:23:in `<main>'
Tasks: TOP => telegram:bot:set_webhook
```
In intercepting `lib/telegram/bot/client.rb:73` the following were being generated for uri and body and leading to error `OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)`:
```
uri:  https://#{my_domain}//bot#{bot_id}:#{bot_token}/setWebhook
body {:url=>"https://#{my_domain}/telegram/#{unique_string_which_does_route_to_controller}", :certificate=>nil, :ip_address=>nil, :drop_pending_updates=>false}
```
The uri has the curiosity of having a double slash.  

The body is quite telling *(I believe one issue is that it states the certificate as nil)*  as if the gem is looking for a client authentication certificate.  Now here is the kicker:  using the API directly
```
curl -F "url=https://#{my_domain}/telegram/#{unique_string_which_does_route_to_controller}" https://api.telegram.org/bot#{bot_id}:#{bot_token}/setWebhook/setWebhook
```
sets the webhook appropriately!  The Telegram server does the cert check and its validation passes.

All other actions, such as `respond_with :message` hit the same `(certificate has expired)` error presumably for the same motive.

Having another application on another server, older gem version 0.14.4, this does not occur.

**side note**  This may be pertinent..  I never managed to start the server with the indications of syntax for the controller:
`class Telegram::WebhookController < Telegram::Bot::UpdatesController`  but had to use, as per the example app
`class TelegramWebhooksController < Telegram::Bot::UpdatesController` with routes set as `telegram_webhook TelegramWebhooksController`

**Comment by kewogc** [comment]
+1 some by get webhook
`2022-03-10 20-12-27.047] [ActiveJob] [Telegram::Bot::Client::AsyncJob] [00235614-1ea9-40fa-ab4b-53106aec141a] Error performing Telegram::Bot::Client::AsyncJob (Job ID: 00235614-1ea9-40
fa-ab4b-53106aec141a) from Async(default) in 238.43ms: OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)):         
/home/deploy/tgbot/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:103:in `connect'                                                                          
/home/deploy/tgbot/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:103:in `ssl_connect'                                                                      
/home/deploy/tgbot/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:41:in `initialize'                                                                        
/home/deploy/tgbot/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:26:in `new'                                                                               
/home/deploy/tgbot/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:26:in `create_socket'                                                                     
/home/deploy/tgbot/shared/bundle/ruby/2.6.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'                                                                    
/home/deploy/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
`

**Comment by printercu** [comment]
Do you use self-signed cert? Do you provide it with CERT option?

See more details in https://github.com/telegram-bot-rb/telegram-bot/wiki/Deployment#webhooks

**Comment by dvodvo** [comment]
Hello,

No, I am not using a self-signed cert, but one issued via lets encrypt.

**Comment by printercu** [comment]
Could you please share a host name of the server you use for a webhook url?

**Comment by joshkurien** [comment]
Apologies, the above comment was because of a misunderstanding...
Simply removing the `server` config from my bot configs resolved my issue
