### ISSUE TITLE
Start telegram:bot:poller and rails server in one time

### ISSUE THREAD

**Issue by anko20094** [telegram-bot-rb/telegram-bot#183]
Is it possible to start rails server and telegram bot at one time as one project?

**Comment by printercu** [comment]
It should be possible: start a thread and run poller inside. Just make sure to take care of code reload if you want to use it in development.

**Comment by printercu** [comment]
What is your use case? Why do you need to run poller inside webserver?

**Comment by anko20094** [comment]
> What is your use case? Why do you need to run poller inside webserver?

I'm developing telegram bot for create image quotes(for myself). And I'd like to make easy way to add new authors and their quotes through web application.
telegram bot: https://t.me/image_quote_bot

**Comment by printercu** [comment]
You can have bot and rails app in a single application. But I won't recommend running poller in production mode. Please see this page for deployment advices https://github.com/telegram-bot-rb/telegram-bot/wiki/Deployment

**Comment by anko20094** [comment]
Looking on this text without example hard to realize what should I do to start rails server and telegram bot on one project the same time... 
**UPD**
I just had to start command `**bin/rake telegram:bot:poller &**`
and after `**rails s &**`
Everythinf is so simple...
