### ISSUE TITLE
How to find all Sessions?

### ISSUE THREAD

**Issue by anko20094** [telegram-bot-rb/telegram-bot#184]
How to find all Sessions? `Session.all` doesn't work... Session not only for current user I need. 
I'm trying to implement blocking user for admin through **callback_query** but can't get previous update datas...
```
 def callback_query(data)
    # binding.pry
    report_update = session[:report_update]
    # binding.pry
    chat_id = Chat.find_by_chat_id(chat['id']).id
    user_id = User.find_by_user_id(from['id']).id
    report  =  Report.where(chat_id: chat_id, reporter_id: user_id)
    binding.pry

    sender_user_id = report_update.dig('message', 'reply_to_message', 'from', 'id')
    reporter_user_id = report_update.dig('message', 'chat', 'id')
    # binding.pry
    case data
    when 'restrict_messages_for_sender'
      answer_callback_query t('.alert'), show_alert: true
      bot.restrict_chat_member(chat_id: chat_id, user_id: sender_user_id, permissions: {can_send_messages: true}.to_json, until_date: (Time.now + 1.hours).to_i)
    when 'restrict_messages_for_reporter'
      answer_callback_query t('.no_alert')
      bot.restrict_chat_member(chat_id: chat_id, user_id: reporter_user_id, permissions: {can_send_messages: true}.to_json, until_date: (Time.now + 1.hours).to_i)
    when 'ban_for_sender'
      answer_callback_query t('.no_alert')
      bot.ban_chat_member(chat_id: chat_id, user_id: sender_user_id)
    when 'ban_for_reporter'
      answer_callback_query t('.no_alert')
      bot.ban_chat_member(chat_id: chat_id, user_id: reporter_user_id)
    end
  end
```

**Comment by printercu** [comment]
Why do you sessions to block them? I see that you have User object, you probably need to block them there.

Sessions are managed by pluggable storage engine, and usually they must be considered as a temporary storage for data that is not critical and can be lost. So relying on session is probably not a good idea.

Anyway, most likely you can query understanding storage directly to get all records. For example redis has KEYS command.

**Comment by anko20094** [comment]
I use session to pass first datas from variable `update` that came to custom action` 'report!'` to another action `'callback_query'` where I need to use those datas....
I don't know how to save first datas from variable `update` from action `'report!' ` in another action `'callback_query'`....

**Comment by anko20094** [comment]
So, is there way to find all Sessions like in rails `Session.all`?

**Comment by printercu** [comment]
No
