### ISSUE TITLE
Per-message session in stubbed bot

### ISSUE THREAD

**Issue by cschuijt** [telegram-bot-rb/telegram-bot#186]
Hey there! I'm working on a bot which can give paginated outputs, eg. there are more than five results and so the message paginates it like so:

![Paginated results](https://cdn.discordapp.com/attachments/231862217220423680/1011375712063717466/unknown.png)

To implement this, I'm using a custom session key that uses chat ID and the ID of the message the bot sends here. That way, paginated lists can exist alongside each other without the next sent list in a chat breaking the previous one. This is the code in the concern I made for it:

```rb
# controllers/telegram_players_controller.rb
result = respond_with :message, text: build_matches_header(@matches, options),
             reply_markup: {inline_keyboard: build_paginated_buttons(@matches)}
message_session(result['result']['message_id']) # assigning the right session ID
message_session[:items] = @matches # etc etc

# controllers/concerns/message_session.rb
def message_session(message_id=nil)
  @_message_session ||= self.class.build_session(chat && message_id &&
                        "#{bot.username}:#{chat['id']}:#{message_id}")
end
```

This all works just fine in practice. The problem I'm currently running into is that, when stubbing the bot during tests, I don't appear to get back any kind of message ID, so my code breaks when trying to fetch it from the `result` hash:

```rb
# result hash in development
{"ok"=>true,
 "result"=>
  {"message_id"=>1041,
   "from"=>{"id"=>5427946583, "is_bot"=>true, "first_name"=>"Gem Test", "username"=>"dotagem_test_bot"},
   "chat"=>{"id"=>151769956, "first_name"=>"Daniel 💎", "username"=>"danvb", "type"=>"private"},
   "date"=>1662120881,
   "text"=>"Matches\n" + "Playing as Spectre\n" + "58 results",
   "reply_markup"=>
    {"inline_keyboard"=>
      [[{"text"=>"W 35min D 14/3/20 Spectre over 1 year ago", "callback_data"=>"nothing:0"}],
       [{"text"=>"W 39min R 14/5/16 Spectre almost 2 years ago", "callback_data"=>"nothing:0"}],
       [{"text"=>"W 54min R 17/4/23 Spectre almost 2 years ago", "callback_data"=>"nothing:0"}],
       [{"text"=>"L 41min D 6/5/12 Spectre almost 2 years ago", "callback_data"=>"nothing:0"}],
       [{"text"=>"L 48min D 8/8/14 Spectre about 2 years ago", "callback_data"=>"nothing:0"}],
       [{"text"=>"1 / 12", "callback_data"=>"nothing:0"},
        {"text"=>">", "callback_data"=>"pagination:2"},
        {"text"=>">>|", "callback_data"=>"pagination:12"}]]}}}

# result array in testing
[{:text=>"Matches\n" + "0 results", :reply_markup=>{:inline_keyboard=>[]}, :chat_id=>456}]
```
The results hash doesn't even appear to be a hash at all when stubbing the bot, returning limited data in a different format. Here's the self-explanatory test result I get:
```
casper@Casper-ROG:~/dotagem$ rspec
....F.....................

Failures:

  1) TelegramPlayersController#matches! without arguments should return the most recent matches
     Failure/Error: message_session(result['result']['message_id'])
     
     TypeError:
       no implicit conversion of String into Integer
     # ./app/controllers/telegram_players_controller.rb:49:in `[]'
     # ./app/controllers/telegram_players_controller.rb:49:in `matches!'
```
I guess my question is, is there any way to test my bot with this setup, or to get access to a message_id-like value while the bot is stubbed? Did I miss something or do something weird? Thanks in advance!

**Comment by printercu** [comment]
Hey. It looks like the error comes from `matches` method because something stubbed as array instead of hash. Could you share method on line 49?

**Comment by cschuijt** [comment]
It is stubbed as an array instead of a hash. The entire method in TelegramPlayersController is a bit long-winded, but the relevant part looks like this:

```rb
  def matches!(*args)
    # Things that happen before the snippet: determining whose matches we're looking for, collecting
    # arguments, sending an API request and assigning the data to @matches
    # Below is line 48:
    result = respond_with :message, text: build_matches_header(@matches, options),
             reply_markup: {inline_keyboard: build_paginated_buttons(@matches)}
    message_session(result['result']['message_id']) # This is the line that causes the error
    message_session[:items] = @matches
    message_session[:page] = 1
  end
```
The error I get makes sense to me: doing `hash["key"]` works but doing `array["key"]` is a TypeError. The underlying issue for my use case is that the array doesn't include anything resembling a message ID which I could use to store my session data, so changing it from an array to a hash wouldn't help. My code would just fail one step down in the `message_session` method because a message ID won't be given.

To see what was happening under the hood, I used `pp(result)` before that line to see what I actually got back in a test environment, which I posted in my last message as well. While the bot is stubbed, the only things we really get back besides the message itself is a chat ID. This makes sense in a way, because you only get a message ID once Telegram has confirmed that the message was actually posted, and we don't do that while the bot is stubbed. But it puts me in a tough spot because my bot stores this stuff in a session by message ID, and I don't see any way of making that work in a test environment without some hacky fixed ID workarounds.

**Comment by printercu** [comment]
Oh, I see now that you use api response. ClientStub#request returns the input which is wrong for your case. You can try to stub response with something like `expect(bot).to receive(:request) { response_stub }`

**Comment by cschuijt** [comment]
Thanks for the tip! Stubbing the `request` method works in the sense that my bot's code runs as expected (with the stubbed message ID), but afterwards I had some trouble figuring out how to test what actually happened. When you stub `request`, no requests are actually made, so helpers like `respond_with_message` or even `bot.requests` come back empty. In the end, I wrote a stub that hits the original method (with the real message) and then returns a (fake) message ID to make everything work on both ends, like so:

```rb
 it "should return the most recent matches" do
   request_method = bot.method(:request)
   expect(bot).to receive(:request) do |*args|
     request_method.call(*args)
     {"ok"=>true, "result"=>{"message_id"=>1234}}
   end
   expect { dispatch_message("/matches", from: {id: user.telegram_id}) }
   .to respond_with_message(/0 results/)
end
```
This test passes, and always evaluates the original message rather than the mocked one. Thanks!

**Comment by printercu** [comment]
You can try .and_call_original.and_return or use this method: https://relishapp.com/rspec/rspec-mocks/v/3-11/docs/configuring-responses/wrapping-the-original-implementation

**Comment by cschuijt** [comment]
I did try stacking `and_call_original` but it unfortunately doesn't work. If you do it like `.and_call_original.and_return` it'll error out and say it can't be modified past that point, if you do it the other way around it'll just use the original. `and_wrap_original` looks cleaner than what I wrote before, so I'll use that instead!
