### ISSUE TITLE
chat_id should take channel usernames as well

### ISSUE THREAD

**Issue by cschuijt** [telegram-bot-rb/telegram-bot#187]
According to the Telegram API specs, `sendMessage` allows me to pass a channel username in the format `@channelusername` instead of a chat ID. As long as the bot is an admin in that channel, this should work. However, when I call `bot.send_message()`, no form of string input is possible for `:chat_id`, it will always give me a bad request: chat not found error. It's not a huge deal for me as I can just point the bot to the right numerical chat ID instead and it'll work, but being able to paste the channel name in would be a nice touch, and on par with the Telegram API.

**Comment by printercu** [comment]
Hey, good find! Did you try it calling a bot's method or a controller helper? What error is returned? 

Could you please give a link to doc that describes this feature? Bot methods don't do anything with request body and just serialize it, so I expect them to not fail in the cases allowed by telegram.

**Comment by cschuijt** [comment]
I'm having some trouble reproducing this today. Chances are I messed up passing the channel name from credentials, since @ is a reserved character in YAML. When using `Telegram.bot.send_message()`, I'm able to pass strings and post to channels just fine. Sorry!
