### ISSUE TITLE
Add the context action to '_handle_action_missing'

### ISSUE THREAD

**Issue by anko20094** [telegram-bot-rb/telegram-bot#189]
Hello, may I ask you to add  context action to '_handle_action_missing' method as it works for usuall actions.
Because now if there is no context action I have error:
```
pry(TelegramWebhooksRouter)> controller.instance_method(:add_moderator)
NameError: undefined method `add_moderator' for class `TelegramReputationController'
from (pry):4:in `instance_method'
[4] pry(TelegramWebhooksRouter)> exit
The context action 'add_moderator' is not found in TelegramReputationController
/home/danyil/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/telegram-bot-0.15.6/lib/telegram/bot/updates_controller/message_context.rb:72:in `action_for_message_context'
/home/danyil/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/telegram-bot-0.15.6/lib/telegram/bot/updates_controller/message_context.rb:54:in `action_for_message'
/home/danyil/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/telegram-bot-0.15.6/lib/telegram/bot/updates_controller.rb:191:in `action_for_payload'
/home/danyil/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/telegram-bot-0.15.6/lib/telegram/bot/updates_controller.rb:160:in `dispatch'
/home/danyil/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/telegram-bot-0.15.6/lib/telegram/bot/updates_controller.rb:109:in `dispatch'
/mnt/c/Users/Danyil/Desktop/uachatsbot/app/controllers/telegram_webhooks_router.rb:23:in `block in dispatch'
/mnt/c/Users/Danyil/Desktop/uachatsbot/app/controllers/telegram_webhooks_router.rb:21:in `each'
/mnt/c/Users/Danyil/Desktop/uachatsbot/app/controllers/telegram_webhooks_router.rb:21:in `dispatch'
```

**Comment by anko20094** [comment]
Or can you suggest some good way how to separate logic of work by controllers?
For example if we have some logic for: admin, reputation, report etc
For now, I'm doing it in next way:
![image](https://user-images.githubusercontent.com/31440971/194946395-0596cbdb-8682-46f1-8aab-31f1e63bd438.png)

**Comment by printercu** [comment]
You can try approaches from https://github.com/telegram-bot-rb/telegram-bot/wiki/Multiple-controllers-for-single-bot

 Regarding exception, you can use different sessions for contexts in different controllers (See message_context.rb). But it feels wrong that context from one controller propagated to another one. Probably it should be cleared in some actions.

Also you can override action_for_message_context and rescue exception.

**Comment by anko20094** [comment]
Alright, I'll try these options, thanks
