### ISSUE TITLE
Add delimer config to CallbackQueryContext 

### ISSUE THREAD

**Issue by mario-amazing** [telegram-bot-rb/telegram-bot#191]
In some cases, CallbackQuery parameters should not contain `:`

Could you add an option to customize it?

Possible solutions: from config or constant **CONTEXT_DELIMER = ':'** in **CallbackQueryContext**

**Comment by mario-amazing** [comment]
@printercu 
When I need to "appointment:#{date}:#{time} #=> time have "17:55" format and : parser identifies as split for new parameters.

it would be nice to have a single separator style, what do you think?

**Comment by printercu** [comment]
As i see in the code it should not be an issue because only first colon is used to detect prefix. Could you please share code example that works not as expected?

**Comment by mario-amazing** [comment]
You are correct, this is not the issue.
But when I have appointments domain, I have a lot of time format with `:`, and when I want to implement back_button I need to mix delimers:
```ruby
  def back_button(text: t('telegram_webhook.buttons.back'), steps_back: 1)
    callback_name, params = payload['data'].split(':', 2)
    back_callback_data = "#{callback_name}:#{params.split('|')[0...-steps_back].join('|')}"
    { text: text, callback_data: back_callback_data }
  end
```

**Comment by printercu** [comment]
I see. You can override this method: https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/callback_query_context.rb#L28

I'm not sure about adding an option for this now as it'll also add a bit of complexity. Please let me know if overriding the method doesn't help.
