### ISSUE TITLE
SimpleCov with ClientStub

### ISSUE THREAD

**Issue by mario-amazing** [telegram-bot-rb/telegram-bot#194]
SimpleCov doesn't see request to TelegramWebhookControlle controllers with ClientStub.
```ruby
Telegram.reset_bots
Telegram::Bot::ClientStub.stub_all!
```
<img width="930" alt="image" src="https://user-images.githubusercontent.com/9537753/209968039-3824b6a8-b5ff-4b18-9e58-04a45947bf32.png">

How to fix this behaviour?

**Comment by printercu** [comment]
stub_all! doesn't affect coverage. Is coverage collected for other classes in other tests?

**Comment by mario-amazing** [comment]
You are right, stub_all does not affect this. But the coverage is still 0%.
But the coverage is empty only for telegram controllers
<img width="951" alt="image" src="https://user-images.githubusercontent.com/9537753/210114729-c2dd516a-9830-485b-bfd2-1f587dc203ad.png">

**Comment by mario-amazing** [comment]
Found solution, simplecov should be the first line in rails_helper:
```ruby
require 'simplecov'
SimpleCov.start 'rails'

Telegram.reset_bots
Telegram::Bot::ClientStub.stub_all!
```
