### ISSUE TITLE
API 6.4 has_spoiler not working 

### ISSUE THREAD

**Issue by mario-amazing** [telegram-bot-rb/telegram-bot#196]
the `has_spoiler` parameter is ignored:
```ruby 
respond_with :photo, photo: Rails.public_path.join("images/test.jpeg").open, caption: t('.content'), has_spoiler: true
```

**Comment by printercu** [comment]
Do you get any exception or it's silently has no effect?

**Comment by mario-amazing** [comment]
> Do you get any exception or it's silently has no effect?

silent

**Comment by mario-amazing** [comment]
I'he tested it on MacOs with the latest version `9.3.241552 Stable`
<img width="613" alt="image" src="https://user-images.githubusercontent.com/9537753/211585244-8839459d-cb0f-4496-8b05-939c1c565eab.png">

**Comment by printercu** [comment]
Does it have "hide with spoiler" feature?

**Comment by mario-amazing** [comment]
Yeap, 
<img width="263" alt="image" src="https://user-images.githubusercontent.com/9537753/211602537-e3b99d17-d756-42cf-ad21-319d638d5ef2.png">

**Comment by printercu** [comment]
Could you please test that has_spoiler works when sending photo using simple curl request?

I'm confused because gem doesn't modify these params and it looks more like a bot api bug.

**Comment by mario-amazing** [comment]
Really weird, but now it works))
Thanks for you time!!!
