### ISSUE TITLE
EditMessageMedia not working

### ISSUE THREAD

**Issue by mario-amazing** [telegram-bot-rb/telegram-bot#197]
`EditMessageMedia` not working in the same way as `send_media_group`
```ruby
edit_message :media, media: { type: 'photo', media: Rails.public_path.join("test.jpeg").open }
```
https://core.telegram.org/bots/api#editmessagemedia

related to: https://github.com/telegram-bot-rb/telegram-bot/issues/167

**Comment by printercu** [comment]
Thanks for reporting! Fixed in 0.15.7.
