### ISSUE TITLE
Allow to subscribe to "chat_member" updates when using web hooks

### ISSUE THREAD

**Issue by webbastelbude** [telegram-bot-rb/telegram-bot#199]
As i understand from the API documentation when using web hooks and "allowed_updates" is not set it will not subscribe to the "chat_member" updates by default.

How can I subscribe to these updates?

**Comment by printercu** [comment]
Hey, at the moment rake tasks doesn't support this param. I'll add it in a week or so. Meanwhile you can just call bot.set_webhook() from a console passing all necessary params.

**Comment by webbastelbude** [comment]
Thank you very much ! Im asking myself as well if we should add the possibility to refresh the web hook automatically if the 
pending_update_count is higher than a certain threshold.
Because the documentation said if for example there will be a new certificate the web hook need to be renewed. Im not sure if this is the case if the certificate is handled externally e.g. by a load balancer in front of the application or if this is only the case if I specify the cert via the webhook.
