### ISSUE TITLE
Can I get contact information?

### ISSUE THREAD

**Issue by ytrrty** [telegram-bot-rb/telegram-bot#20]
https://core.telegram.org/bots/api#keyboardbutton

How can I get user phone and location by gem?
Thanks!

**Comment by printercu** [comment]
I haven't read docs. What does they say, which field will contain location?

**Comment by printercu** [comment]
Closing because of no response.

**Comment by Evshved** [comment]
https://wptele.ga/docs/get-use-user-location/

**Comment by mario-amazing** [comment]
@printercu, hi have the same question in 2021. Could reopen this issue and have with a solution?
Thanks in advice

**Comment by printercu** [comment]
Hi! I'm not sure it's related to the the gem itself. I cannot help with this question. If there is no info on this in bots api docs, then StackOverflow could be a better option for this question: you'll get response from users of different bot libraries.
