### ISSUE TITLE
Webhook secret_token verification

### ISSUE THREAD

**Issue by kshnurov** [telegram-bot-rb/telegram-bot#201]
Webhook may have a [secret_token](https://core.telegram.org/bots/api#setwebhook) set, which will be sent in a `X-Telegram-Bot-Api-Secret-Token` header and could be verified.
Didn't find a default functionality for that, tried to add a `before_action`, but it fails with `undefined local variable or method 'request' for #<Telegram::WebhookController:0x0000000011acd8>`.

Am I missing something? How do I access request headers?
I guess the only way is to override middleware?

**Comment by printercu** [comment]
Yes, it doesn't support token verification at the moment. As a workaround you can have something like this
```ruby
Telegram::Bot::Middleware.prepend(Module.new do
  def call(env)
    verify_token(env)
    super
  end
end)
```

**Comment by kshnurov** [comment]
@printercu thank you! I'd like to avoid monkey-patching, is there a specific reason why the `request` is [not passed down](https://github.com/telegram-bot-rb/telegram-bot/blob/be74094c9051f59a124112e369f4d2c3e5ffeca3/lib/telegram/bot/middleware.rb#L19) to a controller's `dispatch` and not set there?

**Comment by printercu** [comment]
Because it's not available in the poller mode. Maybe it makes sense to pass it in the webhook mode and set to nil in the poller mode.

**Comment by kshnurov** [comment]
@printercu definitely.
