### ISSUE TITLE
Telegram-bot poller mode with sentry

### ISSUE THREAD

**Issue by mario-amazing** [telegram-bot-rb/telegram-bot#203]
In poller mode, the bot doesn't send raise_error to sentry. (OR rewrites logs somehow) `LOG_TO_STDOUT` doesn't help
Bot sends only [`OpenSSL::SSL::SSLError`] error.

Expected behavior: same as with `rails s` -> `webhook mode`. Sends all errors to sentry 

Gemfile:
```ruby
gem "sentry-ruby" 
gem "sentry-rails"
```

config/initializers/sentry.rb
```ruby
Sentry.init do |config|
  config.dsn = 'DSN'
  config.enabled_environments = %w[production]

  config.traces_sample_rate = 0
end
```

**Comment by mario-amazing** [comment]
I think the issue in the Logger inside the bot poller
If you have another vision of why the behavior above could be, explain it, please)

**Comment by printercu** [comment]
https://github.com/getsentry/sentry-ruby/blob/master/sentry-rails/lib/sentry/rails/railtie.rb#L10 this is where sentry installs plugin into action_controller.

Obviously it doesn't install such plugin for telegram bot poller. So you can either ask them for such plugin or implement it yourself. With a link I provided in the previous comment you can wrap `super` call with a code that will capture exception and send it to sentry. It will be something like this: https://github.com/getsentry/sentry-ruby/blob/803ba7394bc8301bec7c3de6c78c4b019214eb8f/sentry-ruby/lib/sentry/rack/capture_exceptions.rb#L12
