### ISSUE TITLE
[Feature request] Add a caption to sendMediaGroup

### ISSUE THREAD

**Issue by mario-amazing** [telegram-bot-rb/telegram-bot#208]
[SendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup) don't have it's own caption parametr.
Solution is to add it to the first media as described [here](https://stackoverflow.com/a/58895281/7121891).

Current solution(add index caption under the hood):
```ruby
respond_with :media_group, media: media_group

def media_group
  bot_session['files_ids'].map.with_index { |file_id, index| { type: 'photo', media: file_id }.merge(index == 0 ? { caption: t('.content') } : {}) }
end
```
Request Feature:
```ruby
respond_with :media_group, media: media_group, caption: t('.content')
```

**Comment by printercu** [comment]
Thanks for figuring out the solution! These [helpers](https://github.com/telegram-bot-rb/telegram-bot/blob/f0c5222c8fe6b59e50f2e0be2cc2a971e6063417/lib/telegram/bot/updates_controller/reply_helpers.rb#L10-L22) were made as simple as possible to keep API concise yet extensible and also less opinionated. This makes it easier to support gem.

I've added similar method to the [wiki](https://github.com/telegram-bot-rb/telegram-bot/wiki/Basic-workarounds#setting-a-caption-for-a-media-group). This method can be used like this:
```ruby
respond_with :media_group, media: set_media_group_caption(media_group, t('.content'))
```
