### ISSUE TITLE
Ability to set queue name in async mode

### ISSUE THREAD

**Issue by blackst0ne** [telegram-bot-rb/telegram-bot#21]
By default the gem uses `default` as a queue name when `async: true`.  
I would like to set my own queue name for various actions.

**Comment by printercu** [comment]
You can access default job's classes with `Telegram::Bot::Client.default_async_job` & `Telegram::Bot::Botan.default_async_job`, and then `class_eval` (or even try just to call `.queue :smth`, I don't know if it's public).

**Comment by blackst0ne** [comment]
@printercu, thank you!!
Code below is working like a charm (for googlers):
```ruby
Telegram::Bot::Client.default_async_job.queue_name = 'YOUR_QUEUE_NAME'
# do your things in async mode. They will go to YOUR_QUEUE_NAME queue.
```

**Comment by blackst0ne** [comment]
ps: it would be nice to add this information into Readme.

**Comment by printercu** [comment]
Yep. Async mode lacks documentation. Will fix it.
