### ISSUE TITLE
"save_context" method is not working properly in group chat

### ISSUE THREAD

**Issue by Nmerey** [telegram-bot-rb/telegram-bot#215]
When using Poller mode, `save_context` does not trigger passed method when used in group chat but works in bot's chat.

Below is when used in group chat:
![image](https://github.com/telegram-bot-rb/telegram-bot/assets/32390632/1ec7fd73-08ed-484d-b12d-559d39ecb840)

It does not fetch updates:
![image](https://github.com/telegram-bot-rb/telegram-bot/assets/32390632/743099e2-fc27-49ef-9285-0dff9e454b48)

When used in bot's chat `save_context` triggers `get_location` method passed to it:
![image](https://github.com/telegram-bot-rb/telegram-bot/assets/32390632/364c104b-b403-43b4-ab15-ea190674d2b8)

It does fetch updates:
![image](https://github.com/telegram-bot-rb/telegram-bot/assets/32390632/e684e936-e595-4d86-bb63-b7aacf13f78f)

Questions:
1. May it be because of group chat id?
2. Or some new restrictions about fetching updates in Telegram?(Could not find any info about that)

**Comment by printercu** [comment]
Context is based on session. See how to configure session key in docs https://github.com/telegram-bot-rb/telegram-bot#session

By default it only uses user id: https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/session.rb#L33
