### ISSUE TITLE
Strange rspec shared_conext `telegram/bot/integration/rails` behavior

### ISSUE THREAD

**Issue by pozabil** [telegram-bot-rb/telegram-bot#219]
When you `require 'telegram/bot/rspec/integration/rails'` as specified in the [documentation](https://github.com/telegram-bot-rb/telegram-bot/tree/master#testing), the shared_context `telegram/bot/integration/rails` is automatically included in all examples with the `type: request` metadata.

https://github.com/telegram-bot-rb/telegram-bot/blob/a16928267a7bbd75a77c43c54a41f886458524fe/lib/telegram/bot/rspec/integration/rails.rb#L3C73-L3C73

In my opinion, this behavior seems incorrect, as it can interfere with other `type: request` examples unrelated to telegram-bot.

**Comment by pozabil** [comment]
Yes, that's what I observed. Some of my tests with `type: request` started failing because one of the let variables changed, which also was defined within the context of `telegram/bot/callback_query`.
I'm not using the `shared_context_metadata_behavior` setting, and I'm also using `rspec-core` version greater than 3.5.

**Comment by printercu** [comment]
I can not reproduce this. Tested with rspec 3.12. Could you please prepare and share sample app with reproducer?
