### ISSUE TITLE
Strange thing with api_methods.txt

### ISSUE THREAD

**Issue by yart** [telegram-bot-rb/telegram-bot#220]
I can't understand why, but when I'm installing the gem, I'm getting this file with Bot API 5.7. The current one is 6.8, as I see here.

I've reinstalled the gem several times, using bundle.

Did somebody have the same trouble?
![image](https://github.com/telegram-bot-rb/telegram-bot/assets/470045/ab825124-39f7-4029-a887-f51b9d84b488)
![image](https://github.com/telegram-bot-rb/telegram-bot/assets/470045/b404beec-1cb8-4bb8-b029-0dc9fc4c44a2)

**Comment by yart** [comment]
Sure, I can simply download the file and replace the installed one with the downloaded one, but in my opinion, this isn't a good way.

**Comment by printercu** [comment]
Hey, this is because latest commits haven't been released yet. I'll do release in a couple of weeks. Meanwhile you can install gem from master branch.

**Comment by yart** [comment]
Thank you, @printercu! I've forgotten this possibility :slightly_smiling_face:
