### ISSUE TITLE
[Feature] Webhook mode telegram server validation

### ISSUE THREAD

**Issue by mario-amazing** [telegram-bot-rb/telegram-bot#222]
Could you help to add telegram server(149.154.160.0/20 and 91.108.4.0/22) request validation?
https://core.telegram.org/bots/webhooks#the-short-version -> second point

**Comment by printercu** [comment]
#207 is related. It needs to be rebased onto master and tested.

**Comment by mario-amazing** [comment]
> #207 is related. It needs to be rebased onto master and tested.

I've rebased without conflicts and tested. Everything looks fine:
<img width="469" alt="image" src="https://github.com/telegram-bot-rb/telegram-bot/assets/9537753/80ff944d-f552-4e7a-bd50-0836125938ad">

**Comment by mario-amazing** [comment]
Then it could be a simple solution:
```ruby 
redirect_or_raise if IPAddr.new('91.108.4.0/22').include?(request.remote_ip) || IPAddr.new('91.108.4.0/22').include?(request.remote_ip)

**Comment by printercu** [comment]
I'm releasing new version, so closing this one. Feel free to reopen.
