### ISSUE TITLE
New 7.0 API

### ISSUE THREAD

**Issue by kshnurov** [telegram-bot-rb/telegram-bot#226]
[Bot API 7.0 has been released](https://core.telegram.org/bots/api-changelog#december-29-2023), I guess it's time to update methods list in this gem.

**Comment by printercu** [comment]
Fixed in #229 , I'll release 0.17 next week. If you have a chance please give it a try before release

**Comment by kshnurov** [comment]
setMessageReaction works, that's all I needed, thank you!

**Comment by printercu** [comment]
You can always call new methods with bot.request(:setMessageReaction)
