### ISSUE TITLE
Send the message at specific time or when time lapses.

### ISSUE THREAD

**Issue by reach2jeyan** [telegram-bot-rb/telegram-bot#23]
I am sorry, if the question is basic, but as far as I saw the methods of this gem, sends replies, when it receives an input from the user.

Does this gem support the feature like, sending message at a specific time or every hour or when the time lapses?

**Comment by printercu** [comment]
Hi! All you need is to call `bot.send_message(your_message_data)` at any moment: inside sidekiq job, in `POST /admin/send_to_everybody` request, or `.rb` file runnig with crontab.

You may want not to use controller at all, and just check this readme section: https://github.com/telegram-bot-rb/telegram-bot#client

But I think controllers are worth using even just to hold `/start` message (unless you receive messages in any other place, and want to send messages to chat_id's you already have).

**Comment by reach2jeyan** [comment]
> Hi! All you need is to call bot.send_message(your_message_data) at any moment: inside sidekiq job, in POST /admin/send_to_everybody request, or .rb file runnig with crontab.

@printercu Thanks for the response, I just started this yesterday and I am kinda noob at this. 

So, I am running a scheduler program which is a rb file in my windows machine, and want to send a message to the bot every hour.

So inside the scheduler job, i called for require telegram/bot and add `bot.send_message(your_message_data)` to it? is what you mean?

**Comment by printercu** [comment]
You should initialize bot first with `bot = Telegram::Bot.new(token)`. I don't think I can explain all ruby's basics here.

Anyway, you're not able to send message anywhere with bot, just to people who added it and started conversation. You also should store their `chat_id`s and send single message to each other in cycle.

**Comment by reach2jeyan** [comment]
> `You should initialize bot first with bot = Telegram::Bot.new(token)`

Yes! My above answer had this already implemented and still I would get the error when my `scheduler.rb` would run it. Also, I am not trying to send the message to anyone apart from me and the people added in the group with the bot.

The error is 

```
 error:
  27775332     27775332
  27775332     NoMethodError
  27775332     undefined method `run' for Telegram::Bot:Module
  27775332       scheduler.rb:26:in `block in <main>'
```

**Comment by printercu** [comment]
I have an error in my previous comment. This line is from readme: ’Telegram::Bot::Client.new(token, username)’. You can omit username.

**Comment by reach2jeyan** [comment]
I think, I posted this issue in the wrong gem. I am using the gem called `telegram-bot-ruby` and the solutions you are giving me is for the gem `telegram-bot` , which is why, I get the error in the module? 

I haven't installed this gem yet. I am using the other gem. Sorry about that.
