### ISSUE TITLE
[Bug] Frozen string in logger caused excessive logging

### ISSUE THREAD

**Issue by AAraKKe** [telegram-bot-rb/telegram-bot#233]
Hi!

After some time without updating my bot I was doing some maintenance and I noticed that I was getting this error over and over again

```
Could not log "process_action.updates_controller.bot.telegram" event. FrozenError: can't modify frozen String: "Completed in 674ms" 
["/Users/jparaque/.rvm/gems/ruby-2.7.8@meetup/bundler/gems/telegram-bot-b05f17b02b5a/lib/telegram/bot/updates_controller/log_subscriber.rb:22:in `block in process_action'", "/Users/jparaque/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/logger.rb:468:in `add'"
...
```

I was taking a look, and the issue seems to have arisen from the latest update where `frozen_strings_literal` has been added to the file. However, the string for the message [here](https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/log_subscriber.rb#L21-L22) is considered frozen but is used to be modified.

Is this the correct assessment, or am I missing something?

Thanks!

**Comment by printercu** [comment]
Hey, thanks for reporting it. This is a bug that must be fixed, I'll work on it later this week. Interesting, that it was not caught by tests. Maybe there's a rescue in rails code that suppresses these errors.
