### ISSUE TITLE
`respond_with` should stop execution and return from method

### ISSUE THREAD

**Issue by tribals** [telegram-bot-rb/telegram-bot#25]
It is intended to when you `respond_with`, you are done, and should not to explicitly call `return`, is it?

**Comment by printercu** [comment]
I don't think it should be forced for everybody. One can call db queries or save analytics data after responding. I hope you can implement it with something like this:

```ruby
def process(*)
  catch(:responded) { super }
end

def resopond_with(*)
  super
  throw :responded
end
```

**Comment by tribals** [comment]
Thanks for quick answer.

Speaking about explicit return, you are right, i didn't though that there is some work to do after response to chat, like analytics an so on.
