### ISSUE TITLE
RSpec for multiple bots only applied for first defined bot

### ISSUE THREAD

**Issue by arsoedjono** [telegram-bot-rb/telegram-bot#30]
Hi there, I finally enter my second bot to my project. And when I run `rspec` it always failed for my second bot scenarios. I am trying to debug it and I found it both entering the same controller. And yet I found the `controller_path` having the value of `/telegram` instead of `/telegram/{token}`. Maybe it is the root of cause?

Best regards.

**Comment by printercu** [comment]
You should have 2 entries in `routes.rb`, one for each bot. `controller_path` works only if you have configured controller for bot with `telegram_webhooks`. And it works only for bot set with `let` for example. Other way you must define `controller_path` yourself.

If this doesn't help, please provide your `routes.rb` and failing spec.

**Comment by arsoedjono** [comment]
I already have tried setting the `bot` and `controller_path` inside each specs via `let`, but it still ends the same. Here is my `routes.rb` file:

```ruby
Rails.application.routes.draw do
  telegram_webhooks firstbot: TelegramBot::FirstbotController,
                    secondbot: TelegramBot::SecondbotController
end
```

and this is the error when I run it, it's all the same for every scenarios:

```
TelegramBot::SecondbotController#help should send telegram message "This is help"
  Failure/Error: it { should respond_with_message I18n.t("#{prefix}.help") }
    expected to make exactly 1 #<Telegram::Bot::ClientStub#70355521193800(arsoedjono_testing_bot)>.sendMessage requests, with [#<RSpec::Mocks::ArgumentMatchers::HashIncludingMatcher:0x007ff9d9a539a0 @expected={:chat_id=>456, :text=>"This is help"}>], but made 0, and 0 with
  # ./spec/requests/telegram_bots/secondbot/main_spec.rb:8:in `block (3 levels) in <top (required)>'
```

And this is my spec file, just in case:

```ruby
RSpec.describe TelegramBot::SecondbotController, :telegram_bot,
               secondbot: true do
  let(:bot) { Telegram.bots[:secondbot] }
  let(:prefix) { 'telegram_bot.secondbot' }
  let(:controller_path) do
    route_name = Telegram::Bot::RoutesHelper.route_name_for_bot(bot)
    Rails.application.routes.url_helpers.public_send("#{route_name}_path")
  end

  context '#help' do
    subject { -> { dispatch_command :help } }
    it { should respond_with_message I18n.t("#{prefix}.help") }
  end
end
```

Sorry for late reply.

**Comment by arsoedjono** [comment]
Oh, and one more thing. I tried to run in console in different environment for testing this code: `bot.token` (via `Telegram.bots.map { |_, v| v.token }`) and `Telegram.bot_poller_mode?` (I found it in `telegram-bot/lib/telegram/bot/routes_helper.rb:61-62`). And the result are different:

* `rails c`:
  + `Telegram.bots.map { |_, v| v.token }`: `[<firstbot_token>, <secondbot_token>]`
  + `Telegram.bot_poller_mode?`: `true`
* `rails c test`:
  + `Telegram.bots.map { |_, v| v.token }`: `[nil, nil]`
  + `Telegram.bot_poller_mode?`: `false`

**Comment by printercu** [comment]
Seems like you don't have tokens in dev mode, so it route paths for bots are identical. You can check it with `RAILS_ENV=test bin/rails routes`. It uses bot token for route path by default, it's recommended by telegram. Try to add sample different tokens for bots in test environment.

`bot_poller_mode?` doesn't matter in this case, it's used only for poller task.

**Comment by arsoedjono** [comment]
Here I provide is the output of `RAILS_ENV=test bin/rails routes`:

```
                    Prefix Verb URI Pattern Controller#Action
 firstbot_telegram_webhook POST /telegram   #<Telegram::Bot::Middleware(TelegramBot::FirstbotController)>
secondbot_telegram_webhook POST /telegram   #<Telegram::Bot::Middleware(TelegramBot::SecondbotController)>
```

Previously, I was using the same token for both of the bots. I modified it so that they have different tokens, but it still giving the same output.

In the development mode, everything is going fine. It just got stuck when running the specs.

**Comment by printercu** [comment]
Yes, here is the problem. Specs performs requests for now and it for both bots it uses `POST /telegram` request. And always only first rout matches request. So all you need is to setup different tokens for bots in `test` env, so `telegram_webhooks` helper can  generate different paths here: https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/routes_helper.rb#L61

**Comment by arsoedjono** [comment]
I am sorry. The `RAILS_ENV=test bin/rails routes` output I provided before, both bots has already having different tokens, declared in `secrets.yml`. Is it intended that in `test` environment the `URI Pattern` is just only `/telegram` instead of `/telegram/{token}` (such as in `development` mode)?

**Comment by printercu** [comment]
Nope, it must be different. Can you please provide output for `Rails.application.secrets[:telegram]` for dev and test envs (replace actual keys with `key1`, etc.).

**Comment by printercu** [comment]
Sorry. No need for actions now, i'll try to investigate a little.

**Comment by printercu** [comment]
I've found a problem. `ClientStub` is used in tests, and it doesn't respect token setting from settings.

**Comment by printercu** [comment]
For fast workaround you can try to add to spec helpers, before `stub_all!`.

```ruby
    Telegram::Bot::ClientStub.class_eval do
      def initialize(token = nil, username = nil, **options)
        @token = token
        @username = username || options[:username] || token
        reset
      end
    end
```

**Comment by printercu** [comment]
Please check with master.

**Comment by arsoedjono** [comment]
Hi @printercu, I still got the same rspec output. And I debug deeper, and set `binding.pry` at `lib/telegram/bot/client_stub.rb` at the very first of `def initialize`. Its `token` value is already `nil`.

![image](https://cloud.githubusercontent.com/assets/11346444/26098433/e75e5a9a-3a51-11e7-9ef2-3747dfe41256.png)

This is another screenshot of the code which called it, and the token existed there but somehow not parsed to the `initialize` method:

![image](https://cloud.githubusercontent.com/assets/11346444/26098696/c191503c-3a52-11e7-9fcf-d06b714d2213.png)

**Comment by arsoedjono** [comment]
Hi, @printercu. I think I got it. And I got the `rspec` all green now. These are what I modified, based on branch `master`:

* `telegram-bot/lib/telegram/bot/client_stub.rb:7-14`

```ruby
module StubbedConstructor
  def new(*args)
    if self == ClientStub || !ClientStub.stub_all?
      super(args[0]) # here
    else
      ClientStub.new(*args)
    end
  end
end
```

* `telegram-bot/lib/telegram/bot/client_stub.rb:37-41`

```ruby
def initialize(token = nil, username = nil, **options)
  @token = token || options[:token] # and here
  @username = username || options[:username] || token
  reset
end
```

But I don't know if it will affect the other functionalities.

Best regards

**Comment by printercu** [comment]
Thank you! This should be ok, for others to. I need just make this initializer similar to Client's one.

**Comment by arsoedjono** [comment]
And just for information, it runs well even `controller_path` is not defined manually in each bot's specs (use the default `controller_path` given in your gem)

**Comment by printercu** [comment]
Just pushed a fix, can you please give it a try.

**Comment by arsoedjono** [comment]
it works good on me @printercu

**Comment by printercu** [comment]
Cool. Thank you! I'll wait few days and then release is as a patch version.
