### ISSUE TITLE
Message context doesn't run

### ISSUE THREAD

**Issue by arsoedjono** [telegram-bot-rb/telegram-bot#33]
Hi again there, I want to ask whether is there something wrong with the message context or am I doing it wrong. I am implementing message context from the readme and tested it manually but it didn't run well. Here is the screenshot how I did it:

![screen shot 2017-05-28 at 17 19 10](https://cloud.githubusercontent.com/assets/11346444/26527994/4e30125a-43ca-11e7-893b-f9ad30554f6c.png)

Here is the controller I am using:

```ruby
module TelegramBot
  class FlipFlopController < Telegram::Bot::UpdatesController
    include TelegramBot::Constant
    include TelegramBot::FlipFlop
    include Telegram::Bot::UpdatesController::MessageContext
    context_to_action!

    # i also tried this
    # def start(*args)
    #   if args.any?
    #     respond_with :message, text: t('.start.done')
    #   else
    #     save_context :start
    #     respond_with :message, text: t('.start.context')
    #   end
    # end

    def start(user1 = nil, user2 = nil, *args)
      if start_valid?(user1, user2, args)
        if user1 && user2
          start_ff(user1, user2)
        else
          save_context :start
          respond_with :message, text: t('.start.context')
        end
      else
        help_message
      end
    end
end
```

**Comment by printercu** [comment]
Hi! MessageContext requires session. Have you set it up and does it already work?

I see there is no mention about it in readme, I'll add soon.

**Comment by arsoedjono** [comment]
Hi @printercu, does the session different from this line of code?

> https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/message_context.rb#L8

But yet, I added these codes to my file and all specs did run well

```ruby
include Telegram::Bot::UpdatesController::Session
use_session!
```

But it still ran the same as the screenshot I provided

**Comment by printercu** [comment]
Yes, it's included with the MessageContext. But it needs to be configured. See https://github.com/telegram-bot-rb/telegram-bot#session

It's not as simple as for web session, as it can not be just stored in cookies. You need to setup it carefully : while it's ok to use file store in development, and memory store for testing, you need to select appropriate store for your production's multithread/multiprocess environment.

**Comment by arsoedjono** [comment]
Eventually I develop the bot also using redis. And I edited my `config/application.rb` so it have these lines:

```ruby
config.cache_store = :redis_store, "redis://localhost:6379/0/cache", { expires_in: 90.minutes }
config.telegram_updates_controller.session_store = :redis_store,  { expires_in: 1.month }
```

I debugged and found the `session` variable has already containing `{"context"=>:start}` after sending `/start` to the bot, but the message after it (which is `@username1 @username2`) is not received by the poller (it doesn't showed up in the console).

Is there anything else? Or is it because the bot is in a group chat?

Best regards

**Comment by printercu** [comment]
So bot does not receive this message at all? This seems to be not the gem problem. If you use bot in a group chat, make sure that you configured privacy mode: https://core.telegram.org/bots#privacy-mode

**Comment by arsoedjono** [comment]
aahhhh, so the problem is the bot's privacy mode, I have tried it by private message and by group message with privacy mode turned off, it worked well

**Comment by printercu** [comment]
This is nice that you have got everything working! Is this issue resolved?

**Comment by arsoedjono** [comment]
I got it done @printercu, let me close it
