### ISSUE TITLE
How to add style to messages like bold and italic?

### ISSUE THREAD

**Issue by jeanfbrito** [telegram-bot-rb/telegram-bot#34]
> There are two possibilities to get: bold
> 
> Set the parse_mode to markdown and send *bold*
> Set the parse_mode to html and send <b>bold<b>

How can I do to send some text in bold?

**Comment by printercu** [comment]
```
respond_with :message, text: '__bold__', parse_mode: :Markdown
```
https://core.telegram.org/bots/api#sendmessage for more details

Please use StackOverflow for such questions, or even better docs first.
