### ISSUE TITLE
My bot is repeating the sent messages

### ISSUE THREAD

**Issue by jeanfbrito** [telegram-bot-rb/telegram-bot#35]
Any time the bot sends a message, it repeats it alot of times. It happens on reply and even on a send message outside a conversation.
I'm using poller, if it is important. Take a look:

![image](https://user-images.githubusercontent.com/1177482/28257147-dd8963b6-6a9e-11e7-87a5-081390567559.png)

Here is my code, for reference:
https://github.com/jeanfbrito/scrapator/blob/master/app/controllers/telegram_webhooks_controller.rb
I'm using the capistrano deploy example from your template project.

**Comment by printercu** [comment]
Hi! Just checked your `#action_missing` in my bot with poller mode and it worked fine. Do you experience this in both production and dev environments? And can you please provide rails logs for 2 subsequent updates, like this:
```
Processing by TelegramWebhooksController#test
  Update: {"update_id":475625016,"message":{"message_id":478,"from":{...},"chat":{...},"date":1500276504,"text":"/test","entities":[{"type":"bot_command","offset":0,"length":5}]}}
Responded with message
Completed in 97ms (ActiveRecord: 0.0ms)
Processing by TelegramWebhooksController#test
  Update: {"update_id":475625017,"message":{"message_id":480,"from":{...},"chat":{...},"date":1500276716,"text":"/test","entities":[{"type":"bot_command","offset":0,"length":5}]}}
Responded with message
Completed in 122ms (ActiveRecord: 0.0ms)
```

**Comment by jeanfbrito** [comment]
Just in production. Where I can find the log deploying it with capistrano, using your example?
After I started using it, my server is using alot of memory and disk capacity usage is increasing.
![image](https://user-images.githubusercontent.com/1177482/28265409-ead4db00-6ac5-11e7-927c-a86409b3c9c7.png)
Any idea that what is happening?

**Comment by jeanfbrito** [comment]
HA! Each deploy a new poller is created. The problem is on restarting instances on each deploy.

> telegram:bot:poller:restart                                              
01 $HOME/.rbenv/bin/rbenv exec bundle exec bin/telegram_bot_ctl restart  
01 telegram_bot: warning: no instances running. Starting...           

After a reboot, the reply messages got clean again, and after each deploy a new reply started comming.

**Comment by printercu** [comment]
Logs seems to be in `path/to/your/cap/:app_name/current/log/production.log`

**Comment by printercu** [comment]
Interesting. I see you use procman, right? So it doesn't restart poller properly?

**Comment by printercu** [comment]
And there is `after 'deploy:finished', 'telegram:bot:poller:restart'` in `deploy.rb`. This one should run and restart bot, and foreman starts at least one more instance.

**Comment by jeanfbrito** [comment]
Take a look, I'm using delayed_job too, and it restarts. Maybe something with 'daemons gem'?
![image](https://user-images.githubusercontent.com/1177482/28266080-6f580b1a-6ac9-11e7-9015-9a2278597133.png)

**Comment by jeanfbrito** [comment]
> telegram:bot:poller:restart
is not finding the old PID to kill it, then just start a new one

**Comment by jeanfbrito** [comment]
I have added this before the poller call, and now is clean.
`execute "pkill -f telegram_bot"`

This is the delayed_job bin code, maybe will help you:
`#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
Delayed::Command.new(ARGV).daemonize`

**Comment by printercu** [comment]
Ok, i'll check later. And will take a look for my cap setup, I thought i had check it some day just for testing. For now I usually use webhooks.

**Comment by printercu** [comment]
Maybe i've found why it does not work. `bin/telegram_bot_ctl` has dir pointing to `../tmp`, but in `deploy.rb` linked dirs contain only `./tmp/{pids,sockets,cache}`. You can try either to change linked dirs to use whole `./tmp` (this way you will also have logs preserved, while you don't use syslog or something similar), or change dir in `bin/telegram_bot_ctl` to `../tmp/pids`. I will update sample app.
