### ISSUE TITLE
API function and rails server run

### ISSUE THREAD

**Issue by armanlearn** [telegram-bot-rb/telegram-bot#38]
Hi 
sorry this is question not issues but i dont find place to send my question

1- when i run server with "rails s" my robot not work but when use "bin/rake" it work.

2- how i can't use another API method like "users.getUsers" . I want to find user_id with phone number
like this 
https://core.telegram.org/method/users.getUsers

many tanks .

**Comment by printercu** [comment]
Hi!

1. Seems like you have not setup webhooks for your bot. I see there is no single place with all the information about different deploy strategies. Please check this links for more info: 
  - https://github.com/telegram-bot-rb/telegram-bot#deploying
  - https://github.com/telegram-bot-rb/telegram_bot_app#production
  - https://github.com/telegram-bot-rb/rails_template#deployment
  - https://github.com/telegram-bot-rb/telegram-bot/wiki/Deployment
2. The link you provided is for telegram client api, it differs from bot api. You may google `telegram client ruby` for such client. This gem provides only bot api integration.

**Comment by armanlearn** [comment]
Hi again I use this repo
https://github.com/telegram-bot-rb/telegram_bot_app
this only work with rake and when i use rails s it not work .what is wrong with this sample ? i think this app use webhook 

tanks

**Comment by armanlearn** [comment]
Dear @printercu i am in localhost 
i find a line in production.rb
#routes.default_url_options = {host: 'yourdomain.com', protocol: 'https'}
if I , uncomment this line what should i write for yourdomain.com ? and protocol also ?


many tanks

**Comment by printercu** [comment]
There are some pros of using webhooks, but you need to have server with https support visible to the internet to accept them. If this is the case, then you need to setup webhook as said in readme. You need to set your domain/ip address in `default_url_options` force https with `protocol: 'https'`.

Other way you have to run poller in production too. You may:
- just run rake task
- use foreman gem to manage processes
- use daemons gem with something like this: https://gist.github.com/printercu/a15c4cab09368d70454c6b1e59c0d7ef

**Comment by printercu** [comment]
You may try to run poller in separate thread within rails application. I have not tested it.

**Comment by printercu** [comment]
@armanlearn did it help? Can the issue be closed?

**Comment by armanlearn** [comment]
I still have problem , i think i should deploy it to server to work with webhook.
in localhost , I cant serve https

**Comment by armanlearn** [comment]
non of them work :( 
I want puller run across other rails controller and model just like normal app.
if I go to production how I compete my app 
I want puma or passenger or whatever run and serve over a port and poller work to.
this is possible ? if not how you create your rails app ?

**Comment by printercu** [comment]
Sorry, this is all the information I know. Please try read readme from the begin to end, make sure you setup everything (routes, secrets on production, webhook, anything else). Check and understand the difference and requirements of webhooks and polling at https://core.telegram.org/bots/api#getting-updates. Make sure you understand why you can not use webhooks in dev environment. Check logs, and setup error collector.

> I want puma or passenger or whatever run and serve over a port and poller work to.

Yes, use separate processes. `rails s` for puma or run passenger app as usual, and `rake telegram:bot:poller` for poller (or use code from gist above).

I have several bots in production. I use webhooks for all of them with letsencrypt certificates. I've tried deploying poller only once when published https://github.com/telegram-bot-rb/rails_template

**Comment by armanlearn** [comment]
tanks.
