### ISSUE TITLE
login with telegram

### ISSUE THREAD

**Issue by armanlearn** [telegram-bot-rb/telegram-bot#39]
Like the other system 
I am interest to find a way user signup with telegram.
I think if there is a form user put phone number on it and get a for number as token in telegram.
when enter token login and this scenario continue each time.
but seems that if user dont start a bot we can send massage to him. do you know any thing about it ?

**Comment by printercu** [comment]
Yes, bot can not send message to user, unless user start chat with him. There are several approaches you can use, one of them is described in https://core.telegram.org/bots#deep-linking-example

I think this questions should be better posted to SO, you can get there more answers with lots of details.

**Comment by armanlearn** [comment]
tanks for your answer

**Comment by Nmerey** [comment]
Now there is a way to signup user using telegram number. It returns token using SHA265 

https://core.telegram.org/widgets/login

Ruby version of checking auth token:
https://gist.github.com/X1ting/6d814e5f9dd0cbc47f8eaed5f2ee65e0

Also, there is a type now that can be used as InlineKeyboardButton for [LoginUrl](https://core.telegram.org/bots/api#loginurl) that allows you to pass info about user with hash token through the link button.
