### ISSUE TITLE
Sidekiq

### ISSUE THREAD

**Issue by top4ek** [telegram-bot-rb/telegram-bot#41]
Hello
I'm using sidekiq with my bot and want to move some logic, data fetching and responses to workers. How can I pass `bot` and `payload` from controller to workers?

**Comment by printercu** [comment]
Hi! There is already Async module, but it has slightly different purpose: it uses queues to send messages. However it's quite similar: it also passes bot and request data to job. Please check `Async` section in readme and async.rb.

Some notice. In my bots the most calls to telegram api are much more time consuming than db requests. So the most gain was achieved by performing responses within jobs, but leaving update processing within main process.

**Comment by top4ek** [comment]
I know about Async mode, it works great, but unfortunately, sometimes theres heavy db requests and I need several job queues with process limits.

**Comment by printercu** [comment]
I hope ActiveJob should serialize `update` hashes fine as they are made from json. You can pass bot the same way as done here https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/async.rb#L53

**Comment by printercu** [comment]
@top4ek closing this one?

**Comment by top4ek** [comment]
@printercu i think yes. Moved out all time consuming jobs to sidekiq.
