### ISSUE TITLE
How to use module TelegramWebhooksRouter in Rails?

### ISSUE THREAD

**Issue by riley-usagi** [telegram-bot-rb/telegram-bot#42]
Can somebody explain last example on [this](https://github.com/telegram-bot-rb/telegram-bot/wiki/Multiple-controllers-for-single-bot) Wiki's page?

**Comment by printercu** [comment]
I can.

**Comment by printercu** [comment]
Bot controller can be any object that responds to `dispatch(bot, update)`. So TelegramWebhooksRouter is actually a controller. You may set it up with `telegram_webhooks` in routes.rb the same way as any other controller.

**Comment by printercu** [comment]
Will add this to wiki.
