### ISSUE TITLE
sequence question

### ISSUE THREAD

**Issue by armanlearn** [telegram-bot-rb/telegram-bot#44]
I know this is not issues but I have a question and I will tankful if you can help me. 👍 
I can't understand how to work if we wan't to get information from user.
for example if we want to ask job application form from user , like robot ask please give me your full name , after save it to database ask what is your degree and so on
I wrote this kind of code:

 respond_with :message, text: 'PLEASE CHOSE A PASSWORD'
 User.where(username: "#{from['id']}", encrypted_password: create_pwd("#{from['text']}") ).first_or_create

 but before user answer question a record save to database, I mean respond_with , don't wait for answer and continue.

tanks

**Comment by printercu** [comment]
Hi! Check this [section in readme](https://github.com/telegram-bot-rb/telegram-bot#message-context) - it's exactly what you want. Make sure you understand how do [sessions](https://github.com/telegram-bot-rb/telegram-bot#session) work, there were some [related issues](https://github.com/telegram-bot-rb/telegram-bot/search?q=session&type=Issues&utf8=%E2%9C%93) to help you avoid common mistakes.

For multiple steps (usually called "wizards") you need slightly modify context managing, however this is easy in this gem:

```ruby

context_handler :create_ticket
def create_ticket(topic = nil, *)
  if topic
    session[:new_ticket_title] = topic
    respond_with text: 'Provide content'
    save_context(:new_ticket_content)
  else
    respond_with text: 'Provide topic'
    save_context(:create_ticket)
  end
end

context_handler :new_ticket_content do |content = nil, *|
  title = session.delete(:new_ticket_title)
  ticket = Ticket.new(title: title, content: content)
  if ticket.save
    # ...
end
```

**Comment by armanlearn** [comment]
Hi again

I add these line to top of code

  include Telegram::Bot::UpdatesController::MessageContext
  include Telegram::Bot::UpdatesController::Session

  use_session!

this is my partcode


  def i_dont_have_account(*)

    respond_with :message, text: 'please chose password :'
    save_context(:new_password)
    
  end

  context_handler :new_password do |pwd = nil, *|
    User.where(username: "#{from['id']}", encrypted_password: create_pwd(pwd) ).first_or_create  
  end

    context_to_action!

but , context_handler jump and don't run this part of code . it seems I should do other thing for session . what should I do for development and what should I do for production


many many tanks

**Comment by printercu** [comment]
Please format you message with code blocks, indentation is broken now. Like this:

    ```ruby
    code
    ```

**Comment by armanlearn** [comment]
Hi
You are right, I update my pervious comment.

many  many tanks

**Comment by printercu** [comment]
Have you performed session store configuration? There is already note on this in readme, i'll add more. New rails app has null-store as default cache store in dev, so it does not save anything between updates.

**Comment by armanlearn** [comment]
it is very short on readme , i cant underestand , can you help me more

**Comment by printercu** [comment]
You need to set `config.telegram_updates_controller.session_store = :file_store`, or better to `:redis_store`. In next release i'll remove fallback to `Rails.cache` and it'll raise error when access session without configured store.

Here is text from readme i'm working on:

## Sessions

This API is very close to ActiveController's session API, but works different
under the hood. Cookies can not be used to store session id or
whole session (like CookieStore does). So it uses key-value store and `session_key`
method to build identifier from update.

Store can be one of numerous `ActiveSupport::Cache` stores.
While `:file_store` is suitable for development and single-server deployments
without heavy load, it doesn't scale well. Key-value databases with persistance
like Redis are more appropriate for production use.

```ruby
# In rails app store can be configured in env files:
config.telegram_updates_controller.session_store = :redis_store, {expires_in: 1.month}

# In other app it can be done for all controllers with:
Telegram::Bot::UpdatesController.session_store = :redis_store, {expires_in: 1.month}
# or for specific one:
OneOfUpdatesController.session_store = :redis_store, {expires_in: 1.month}
```

**Comment by armanlearn** [comment]
Hi

it really get me crazy

I add   `gem 'redis-rails'` to gem file and bundle it to install.

after that I add 

`  Telegram::Bot::UpdatesController.session_store = :redis_store, {expires_in: 1.month}
`
to development.rb and 

`    config.cache_store = :redis_store, "redis://localhost:6379/0/cache", { expires_in: 90.minutes }
`
to application.rb

this is how I use context

`
  def i_dont_have_account(*)

    respond_with :message, text: 'please select a password'
    save_context(:new_password)
    
  end



  context_handler :new_password do |pwd = nil, *|
    User.where(username: "#{from['id']}", encrypted_password: create_pwd(pwd) ).first_or_create  
    #respond_with text: "created !"
  end

`

**Comment by printercu** [comment]
Please start with https://github.com/telegram-bot-rb/telegram_bot_app: run the bot, check that `/memo` command works for you (https://github.com/telegram-bot-rb/telegram_bot_app/blob/master/app/controllers/telegram_webhooks_controller.rb#L13), try to modify it slightly.

Then implement (or just copy paste) this simple command in your bot, make sure it works fine. And only then start working on registrations.

PS. There is "Preview" tab when writing comment to check formatting before posting it.

**Comment by printercu** [comment]
Closing due to lack of response. Feel free to ping me to reopen.
