### ISSUE TITLE
[FAQ] Launch osmand android app from bot

### ISSUE THREAD

**Issue by kirantpatil** [telegram-bot-rb/telegram-bot#46]
Hi,

I would like to launch [osmand](https://github.com/osmandapp/Osmand) android app from bot with source and destination provided.

How to implement it ?

Thanks.

**Comment by kirantpatil** [comment]
I also raised it in Telegram-foss https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/176.

**Comment by printercu** [comment]
I don't know. I'm not sure if this is related to the gem. Please, use StackOverflow for such questions, there are much more users which can be familiar with osmand/java/telegram features.

**Comment by kirantpatil** [comment]
Ok thanks.
