### ISSUE TITLE
send photo and html text

### ISSUE THREAD

**Issue by AlexiaTorres** [telegram-bot-rb/telegram-bot#47]
Hi! when i use _reply_with :photo, photo: File.open('party.jpg')_  there is an error on console:
No such file or directory @ rb_sysopen
Where should I put the images?  I'm using the route: _app/assets/images/_ 

And other thing: its possible use html text in responses? how i do it from controller? I only know do it from views

**Comment by AlexiaTorres** [comment]
I've tried with _**respond_with :photo, photo: File.open(File.join('app/assets/images/','image.png'))**_  but:
_Unsupported argument type: File_

**Comment by printercu** [comment]
> Unsupported argument type: File

Do you use async mode? If so, it does not support sending files by default, as they are not serializable in basic case. There is note about it in readme: https://github.com/telegram-bot-rb/telegram-bot#async-mode.

>  its possible use html text in responses?

Are you looking for something like `respond_with :message, text: '<b>Bold</b>', parse_mode: :HTML`?

**Comment by AlexiaTorres** [comment]
Finally, what I did was to directly use the url of the image.
The html text was silly hahaha, I did not know that en.yml took the line breaks literally
Thanks!!

**Comment by printercu** [comment]
Great that it helps. According to newlines in .yml, there are several ways for multiline string representation with small differences. I've just found great website, that describes all of them: http://yaml-multiline.info/
