### ISSUE TITLE
delete_message

### ISSUE THREAD

**Issue by riley-usagi** [telegram-bot-rb/telegram-bot#48]
Is there an implementation of this method?

**Comment by printercu** [comment]
Are you looking for `bot.delete_message(chat_id:, message_id:)`?

https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/client.rb#L105
https://core.telegram.org/bots/api#deletemessage

Client has all api methods with underscored names. If you have access to any secret method, just use `bot.request('secretEndpoint', params)`.

**Comment by printercu** [comment]
@riley-usagi Can this one be closed?

**Comment by riley-usagi** [comment]
Yes.
