### ISSUE TITLE
Don't know how to use different controllers while still getting session

### ISSUE THREAD

**Issue by AAraKKe** [telegram-bot-rb/telegram-bot#50]
Hi,

I want to create different controllers since my bot functinalities are getting too big and becoming hard to manage only in one controller. My approach is to use what is mentioned [here](https://github.com/telegram-bot-rb/telegram-bot/wiki/Multiple-controllers-for-single-bot), the first case, but I got the following exception:

`session_store is not configured`

How should I proceed to properly find how to deal with it?
Thanks!

**Comment by printercu** [comment]
All you need is to configure session store in all controllers. Here are options from easiest one:

- global configuration
- inherit controllers from single parent, session store config will be inherited
- configure each controller separately.

More on session configuration is in readme: https://github.com/telegram-bot-rb/telegram-bot#session

**Comment by AAraKKe** [comment]
Well, my first approach was your second bullet but it doesn't seem to work or I assume I am doing something wrong since  I haven't worked much with sessions.

I have a base controller for the bot which I use as it were my ApplicationController, all controllers inherits from it. It looks like this:

```ruby
class MitupController < Telegram::Bot::UpdatesController
  include Telegram::Bot::UpdatesController::Session
  use_session!

  before_action :configure_user_and_locale
  around_action :configure_time_zone
  include Telegram::Bot::UpdatesController::MessageContext
  include Telegram::Bot::UpdatesController::CallbackQueryContext
  context_to_action!
  include Telegram::Bot::Botan::ControllerHelpers
 ## I put some methods here to be used with the before_action
end
```

And then, the controller which has the dispatch method defined looks like this

```ruby
class TelegramWebhooksController < MitupController

  class << self
    # Dispatch to the needed controller
    def dispatch(bot, update)
      # Check the update for callback queries
      if update['inline_query']
        InlineQueryController.dispatch(bot, update)
        # I will add more cases for callback_queries and so on
      else
        super
      end
    end
  end

  # Function to handle a message with no context
  def message(message)
# Do things with messages
end
# And more methods 
```

The issue is that if it goes to the InlineQueryController it works fine but as soon as it enters super it crashes, I am assuming that for some reason the session is not present in the UpdatesController once it goes up.

Is there something obviously wrong?

**Comment by AAraKKe** [comment]
Also, in initializers I have this:

```ruby
#initializers/session_store.rb
Rails.application.config.session_store :cookie_store, key: '_telegram_bot_app_session'
```

Shouldn't this already include the global configuration?

**Comment by printercu** [comment]
Please check that section from my 1st comment readme carefully: bot's session store is not related to `Rails.application.config.session_store`, more explanation is in readme. You need to setup `config.telegram_updates_controller.session_store` or `self.session_store=` inside `MitupController `.

**Comment by printercu** [comment]
I'll add note to readme why cookies can not be used: 

Cookies can not be used to store session id or whole session (like CookieStore does): webhooks for all chats come from telegram server which does not use cookies, updates fetched with poller don't have cookies at all.

**Comment by AAraKKe** [comment]
thanks a lot @printercu I have never had to deal with sessions that much (other than use them) which is why I am kind of lost, sorry if this is simple.

I don understand for instance why I need to do this if I use more than one controller but if I use a single controller everything works fine. What is the default session store and how is it defined?

**Comment by printercu** [comment]
Session store is not configured by default. You may face this error, if you have used previous version before and had not actually use session: `session` object is instantiated on every request, but any method on session store is called only when session is was modified or got read. Also there was fallback to `Rails.cache`.

In #45 it was changed to check store configuration when session object instantiated to prevent `undefined method smth for NilClass`. Fallback to `Rails.cache` was also removed because it's NullStore in development by default, which made sessions not working without any errors. In this PR developers are forced to understand and configure session before using it, because it has some significant differences from usual rails sessions.

**Comment by AAraKKe** [comment]
I have been ussing sessions since the beggining, but I have never had to configure anything. I used the telegram bot example in the readme as a start point and I just wanted to know what would you recommend to use a session_store. I am not sure how it saves sessions before from using the bot example since I cannot find any session_store definition and it has been working fine.

What store would you recommend? I have been taking a look at different ones but redis, in heroku, is paid if I want persistent. Active records store I am not sure how efficient would be and memory might not be the best way to go in production. I would really appreciate if you gave some pointers about this, and thanks a lot!

**Comment by printercu** [comment]
Example app uses MemoryStore in dev: https://github.com/telegram-bot-rb/telegram_bot_app/commit/0a1c8a8e1d1bfc4aeed5dc3689482a02ea46d728

Rails does not have much built-in stores: http://api.rubyonrails.org/classes/ActiveSupport/Cache.html. Only MemoryStore and FileStore are useful for session and does not require external app. Select is usually app-specific:

- MemoryStore is cleared on server restart. I think it can be useful only for tests.
- FileStore persists between server restarts. Seems like it locks file for updating values, so it can be used in multi-process envs too.

So I think FileStore is good enough to start with in single-server env. I was able to run redis for all my bots so I used RedisStore for them.

One more advise is to set some expiration for sessions (say, 6 months) to prevent it from bloating.

**Comment by AAraKKe** [comment]
Where do you put your bots? I use heroku butif I wanted to use redits, which seems the best way to go from the quick glance I had yesterday, in heroku the free add-on for redis seems pretty limited.

**Comment by printercu** [comment]
On dedicated servers. You may check aws or google cloud, they both have free tiers. You may use their cloud databases for session_store: if you don't find AS::Store adapter for them, just implement your own with couple of methods like `write/read/delete/exist?` (see all used methods in: https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/session.rb, look for `store.*`)

**Comment by AAraKKe** [comment]
Thanks for all the help. I will try to follow from here myself, I got the bot working with different controllers and I just wanted to undestand a bit better about stores, it helped a lot!

**Comment by AAraKKe** [comment]
And it has now near 2k users hehe, thanks a lot again for this great tool!

**Comment by printercu** [comment]
Welcome!

I just think I'd add "built-with" page to wiki. Can I add link to your bot there?

**Comment by AAraKKe** [comment]
Sure! Feel free to do so
