### ISSUE TITLE
Callback Query RSpec Example

### ISSUE THREAD

**Issue by arsoedjono** [telegram-bot-rb/telegram-bot#52]
Hi @printercu, do you have any example of how to create RSpec test unit for callback queries? I can't found it on the [bot app](https://github.com/telegram-bot-rb/telegram_bot_app) repo. Especially for a callback from inline keyboard.

Best regards

**Comment by printercu** [comment]
Hi! There were missing `let`s, I've just fixed it in 0.12.4: https://github.com/telegram-bot-rb/telegram-bot/commit/384d203b5934cfabe0ff6aa5fa6863e7ab1a3d7e This commit also has some specs for callback queries.

Added commit with such specs to sample app: https://github.com/telegram-bot-rb/telegram_bot_app/commit/c8ff65bd4093ac93106e43d823a736d41daf392c

**Comment by printercu** [comment]
Did it help? Can we close this one?

**Comment by arsoedjono** [comment]
sorry for late answer @printercu 
i think i got it now

thanks
