### ISSUE TITLE
Timeout issue in Heroku for long request

### ISSUE THREAD

**Issue by AAraKKe** [telegram-bot-rb/telegram-bot#53]
Hi!

I just have an issue within heroku and I would like to know if you guys know a way of overcome this.

I have an option that only me as an admin can run to send an update to everyone in the bot. The issue is that when I run it it takes more than 30 seconds to run which is the timeout in Heroku. Nonethless Heroku supports long polling and straming so this things can be avoidd but what is needed is the following:

> Heroku supports HTTP 1.1 features such as long-polling and streaming responses. An application has an initial 30 second window to respond with a single byte back to the client. However, each byte transmitted thereafter (either received from the client or sent by your application) resets a rolling 55 second window. If no data is sent during the 55 second window, the connection will be terminated.

As explained here: https://devcenter.heroku.com/articles/request-timeout

I just would like to know if you what is consider whn talking about a rails app made with this tool a "response back to the client".

**Comment by printercu** [comment]
Hi! I think creating a job to send all the messages would be ok. With rails 5.1 you can use built-in async adapter without any additional libs. In admin panel or within bot's controller you will just have `TelegramBroadcastJob.perform_later(text)` which will return immediately, and the job itself will be performed in other thread. The common pitfall with async adapter - some jobs may be lost when you restart app. But for your case this should not be a problem - just don't restart it when broadcasting :) Later you may switch to sidekiq or any other adapter with persistance.

**Comment by AAraKKe** [comment]
Thanks a lot! Hopefully this will work. I asked before trying because I anticipated that I could have some issues with Heroku and job scheduling but I will try and let you know. Thanks!

**Comment by printercu** [comment]
Hi! Is this issue resolved?

**Comment by AAraKKe** [comment]
Hi! Yes, the job did the job :) thanks!
