### ISSUE TITLE
Not possible to use rescue_from in controller

### ISSUE THREAD

**Issue by zhulik** [telegram-bot-rb/telegram-bot#55]
```
`<class:TelegramWebhooksController>': undefined method `rescue_from' for TelegramWebhooksController:Class (NoMethodError)
```

I know that it's possible to include `ActiveSupport::Rescuable` manually, but it does't work.

**Comment by printercu** [comment]
Does `include ActionController::Rescue` do the trick?

**Comment by zhulik** [comment]
Nope, if you include ActionController::Rescue, method rescue_from will be available, but will do nothing, exception will not be catched.

**Comment by printercu** [comment]
I've found that it calls `#request` in `ActionController::Rescue` which is not available in bot controllers. Here is module i've tested, i'll add it to gem later:

```ruby
  module Telegram::Bot::UpdatesController::Rescue
    extend ActiveSupport::Concern
    include ActiveSupport::Rescuable

    private

    def process_action(*args)
      super
    rescue Exception => exception
      rescue_with_handler(exception) || raise
    end
  end
```

**Comment by zhulik** [comment]
Wonderful, thank you! I hope it will be included by default, just like in Rails=)

**Comment by printercu** [comment]
Added this feature in 45e8a7283f1768446879582a6ec7de58a387daa3 I plan to release it in week or so.

I've decided to keep `rescue Exception` (similar to rails), as it does not restrict end-users and allows them to `rescue_from AnyExceptionClass_EvenNotStandardError, ...`.

**Comment by printercu** [comment]
Closing this one. Feel free to ping me to reopen :)
