### ISSUE TITLE
Helpers are not included by default

### ISSUE THREAD

**Issue by zhulik** [telegram-bot-rb/telegram-bot#56]
I have a few helper modules in `app/helpers` and they are not available from controller by default, even ApplicationHelper. I have to include them explicitly.

**Comment by printercu** [comment]
Hi! Are you talking about views rendering (`.erb`) or making this helpers available inside controllers. First case is not covered by the gem for now. The second one: I've checked rails controllers and helpers are not included to controller by default too. I'm not sure they should be included implicitly, as they are views-rendering related. I think it keeps balance between magic end explicitness. So I'm for explicit includes in this case. WDYT?

**Comment by zhulik** [comment]
Seems like your're right, it's my fault.
