### ISSUE TITLE
Very intricate startup worflow

### ISSUE THREAD

**Issue by zhulik** [telegram-bot-rb/telegram-bot#57]
As I can see, there are some tricks around loading the library and bot's controller. I found this when tried to use `simplecov` gem for my tests. Due to #56 I had to include my helper modules explicitly and noticed, that I don't see the helper in simplecov report.

Seems like the controller code is executed before SimpleCov.start.

**Comment by printercu** [comment]
Can you please provide sample app? I don't remember something complex in loading: controllers and all gem's code and included modules should be already loaded once rails app is loaded (with eager load).

> Seems like the controller code is executed before SimpleCov.start.

As I remember, simplecov should be the placed to the top of rails_helper even before `require '..../environment'`

**Comment by zhulik** [comment]
Actually, Simplecov should be initialized in the top of `spec_helper`. I'll provide you a samle app ASAP

**Comment by printercu** [comment]
@zhulik any updates on this? Is the issue resolved?
