### ISSUE TITLE
context_handler input 'Text' with new line problem

### ISSUE THREAD

**Issue by onesup** [telegram-bot-rb/telegram-bot#66]
I want input long text with new line in chat room. 
So I write code like this.

```
context_handler :mobile_message do |*words|
    context = :mobile_message
    session[context] = words
    puts "@@@@start@@@@@"
    puts "session: #{session[:mobile_message]}"
    puts "@@@@@end@@@@@@"
    respond_with :message, text: "are you sure?", reply_markup: {
      inline_keyboard: [
        [{text: "confirm!", callback_data: 'send_mobile_message:confirm'}],
        [{text: "no", callback_data: 'send_mobile_message:cancel'}]
      ],
      resize_keyboard: true,
    }
  end
```

but ```session[:mobile_message]``` is array with every words that seperated with space without new line how can I do?

**Comment by onesup** [comment]
I monkey patched like this.
```
        # Fetches context and finds handler for it. If message has new command,
        # it has higher priority than contextual action.
        def action_for_message
          val = message_context_session.delete(:context)
          @context = val && val.to_sym
          super || context && begin
            handler = handler_for_context
            words = payload['text'].lines
            puts "@****@@@start@@@@@"
            puts words
            puts "@****@@@@end@@@@@@"
            [true, handler, words || []] if handler
          end
        end
```

**Comment by printercu** [comment]
Context is automatically cleared on the following message. If you want to keep it, you have to call `save_context(:mobile_message)` again inside context_handler.

**Comment by printercu** [comment]
Context is cleared in action_for_message, so it's not cleared for inline callbacks. Make sure to call `save_context(nil)` in `send_mobile_message`.

I suggest using `callback_data: 'cancel_mobile_message:x'` & `callback_data: 'confirm_mobile_message:x'` to keep 'em in separate methods.

**Comment by printercu** [comment]
@onesup Have this helped? Should we close the issue?
