### ISSUE TITLE
Session doesn't work on Heroku

### ISSUE THREAD

**Issue by ManuelFrigerio** [telegram-bot-rb/telegram-bot#70]
Hi,

I've built a simple Bot using your great gem. It works fine locally but on production instead (I'm on Heroku) it doesn't seem to store the session.

In particular, when I run the command `/gym_update_count` and I reply, it replies with the default message.

This is my method:

```
def gym_update_count(*)
    save_context(:gym_count)
    respond_with :message, text: "How many times have you been to the gym in total?"
end

context_handler :gym_count do |count = nil, *|
    user.update(times_in_gym: count)
    respond_with :message, text: '👍 Updated'
end
```

I believe the problem lies in the cache.
I've added RedisCloud to my account, added `gem 'redis-rails', '~> 5'` and changed my `production.rb` file with:

```
config.cache_store = :redis_store, ENV['REDISCLOUD_URL']
config.telegram_updates_controller.session_store = :redis_store, {expires_in: 1.month}
```

What am I doing wrong?

Thanks

**Comment by printercu** [comment]
`cache_store` is not related to `telegram_updates_controller.session_store`. Please try to configure session_store using REDISCLOUD_URL too.

**Comment by ManuelFrigerio** [comment]
I'm not sure I understand. How do I configure session_store using REDISCLOUD_URL?

**Comment by printercu** [comment]
`cache_store` from your config uses `REDISCLOUD_URL`, while `session_store` - does not. Actually it's not connected at all, but errors are suppressed unless store is configured with `raise_errors: true`: https://github.com/redis-store/redis-activesupport/blob/master/lib/active_support/cache/redis_store.rb#L286. I don't know why they suppress errors by default, this looks very strange to me. Will add a note about this to readme.

All you need is to configure session_store using url similar to cache_store:

```ruby
config.telegram_updates_controller.session_store = :redis_store, {
  url: ENV['REDISCLOUD_URL'],
  expires_in: 1.month,
}
```
All available options are in gem docs: https://github.com/redis-store/redis-activesupport/blob/master/lib/active_support/cache/redis_store.rb#L17

**Comment by ManuelFrigerio** [comment]
That fixed it! Thanks @printercu 

PS: I think you should add that to the Readme ;)
