### ISSUE TITLE
Typed responses: get_chat doesn't return Telegram::Bot::Types::Chat

### ISSUE THREAD

**Issue by asgerb** [telegram-bot-rb/telegram-bot#75]
Hey there, thanks for a lovely gem! 🙂

I'm trying to use `get_chat` and was hoping to get a typed response, but alas it returns me a hash:

```ruby
Telegram.bot.get_chat(chat_id: ENV['TELEGRAM_CHAT_ID']).class
#  => Hash 
```

I'm guessing this is not on purpose, but rather just a missing detail?

If so I can try my hand at a PR if you're interested. I'm guessing it should be quite straightforward to implement.

**Comment by asgerb** [comment]
I dug me way to [telegram/bot/client/typed_response.rb](https://github.com/telegram-bot-rb/telegram-bot/blob/eb24816e1ef46667165d818549b0257aafd211dc/lib/telegram/bot/client/typed_response.rb#L10), which seems to just be missing the line: `getChat: :Chat,`

**Comment by printercu** [comment]
Hi! Please try master. Also please update types gem, `telegram-bot-types, '~> 0.6'` is required. I don't know how to properly add this optional dependency to gemspec.

**Comment by printercu** [comment]
I've now extracted all types definitions to that gem.
