### ISSUE TITLE
How to scale horizontally using a Load balancer?

### ISSUE THREAD

**Issue by bbc4468** [telegram-bot-rb/telegram-bot#86]
Not considering rails
I am running the bot as an independent ruby process listening to messages. I want to horizontally scale this setup. How do I enable sticky session over the load balancer? 

I want all messages coming from a particular chat/user to route to the same machine.

**Comment by printercu** [comment]
This depends on a lot of things: poller-/webhooks-mode, used front-end  http server, app architecture, etc. And can be implemented in different ways: balancing using front-end http server (ex., nginx) or in ruby app.

This question is not related to telegram-bot itself, I hope stackoverflow or ruby/telegram related forums are better place for this discussion. You can get feedback from other language developers there, who faced same problem.

**Comment by bbc4468** [comment]
Ok. thanks! Closing the thread.
