### ISSUE TITLE
How do I hide the inline-keyboard once the user has selected a preference?

### ISSUE THREAD

**Issue by bctoh** [telegram-bot-rb/telegram-bot#87]

**Comment by printercu** [comment]
Have you tried `editMessageReplyMarkup` with `reply_markup: {inline_keyboard: []}`?

**Comment by bctoh** [comment]
@printercu I get that logic and I think that would work. Just figuring out how to write that in the controller. Any chance you could show me how you'd write it with a check to see if user selected something? Thx for the prompt response 🙏

**Comment by printercu** [comment]
There is an simple example of callback query in sample app: https://github.com/telegram-bot-rb/telegram_bot_app/blob/master/app/controllers/telegram_webhooks_controller.rb#L42-L60

Add `edit_message :reply_markup, reply_markup: {inline_keyboard: []}` along with `answer_callback_query`. See telegram api docs https://core.telegram.org/bots/api#updating-messages for options and reply helpers to see how it works: https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/reply_helpers.rb

PS. See look for CallbackQueryContext in readme, it can help with heavy callback queries usage.

**Comment by bctoh** [comment]
@printercu ah mate, this is so helpful! thank you so much, it worked like a charm! 🍻

**Comment by printercu** [comment]
Nice to hear! Closing this one?
