### ISSUE TITLE
How to set expire session value?

### ISSUE THREAD

**Issue by boggddan** [telegram-bot-rb/telegram-bot#92]
Hi, Printercu.
Could you help me set expire session value?

Radis have methods for set expire: [setex](https://www.rubydoc.info/github/ezmobius/redis-rb/Redis:setex) and [expire](https://www.rubydoc.info/github/ezmobius/redis-rb/Redis:expire)

This, code isn't work.
```ruby
  session.expire(:lang, 5)
```

Thank's.

P.S.  Telegram-bot 0.14 is awesome, thanks for you work.

**Comment by printercu** [comment]
All values of `session` are backed by single hash stored in redis, so it's not possible to expire one particular key, keeping others. The most common, and "officially supported" option is to set expiration timeout for all sessions (see here https://github.com/telegram-bot-rb/telegram-bot#session).

You can try to use `redis_client.setex(seesion.id)` to set expiration for some sessions. But I think the better option is to save this values in redis in your custom namespace.

**Comment by boggddan** [comment]
Thank's
I completed this trouble this way

```ruby
  def session_key_lang
    "#{session_key}_lang"
  end

  def session_lang
    ActiveSupport::Cache.lookup_store(config.session_store).read(session_key_lang)
  end

  def session_lang=(value)
    ActiveSupport::Cache.lookup_store(config.session_store).write(session_key_lang, value, expires_in: 5.minutes)
  end

  def lang
    unless session_lang
      self.session_lang = user \
        ? user.lang \
        : from['language_code']&.downcase&.include?('ru') ? 'ru' : 'en'
    end

    session_lang
  end
```

Could you mind to advise  the better way to complete this task? Thanks

**Comment by printercu** [comment]
Looks good. You can try to simplify it a little:

```ruby
  def session_key_lang
    "#{session_key}_lang"
  end

  def session_lang
    self.class.session_store.read(session_key_lang)
  end

  def session_lang=(value)
    self.class.session_store.write(session_key_lang, value, expires_in: 5.minutes)
  end

  def lang
    self.session_lang ||= user&.lang || lang_from_update
  end

  def lang_from_update
    from['language_code']&.downcase&.include?('ru') ? 'ru' : 'en'
  end
```

**Comment by printercu** [comment]
А вы юзера не загружаете в тех апдейтах, в которых используется lang? Мне такое решение кажется не очень подходящим, т.к. после обновления на сайте пользователь будет продолжать видеть старые данные ещё 4 минуты. Может быть лучше кэшировать юзера в редисе и сбрасывать кэш в афтер-сэйв.

**Comment by boggddan** [comment]
Спасибо, отличная идея, но теперь как бы вопрос, как мне с модели, достучаться до нужного ключа в Redis, что бы сделать замену? 
Ну я понимаю, что ключом у меня будет session_key, в котором хранится hash с нужными значениями, но как к самому Redis достучаться?
Спасибо.

**Comment by printercu** [comment]
Тут наоборот - контроллер получает данные от модели, а модель сама определяет когда сбрасывать кэш. Примерно так:

```ruby
class User
  class << self
    def fetch(id)
      fetch_from_redis(key_for(id)) { find(id) } 
    end
  end

  after_commit { delete_from_redis(key_for_id) }
end
```

Все довольно просто. Есть гем с похожим функционалом  - https://github.com/Shopify/identity_cache.

Вообще, лучше логику держать в моделях :)

**Comment by boggddan** [comment]
Спасибо, ну про то что логику перенести в модель это ясно. Еще отдельное спасибо, за интересную идею кэшировать саму модель. Но пока хочу реализовать простым путем: по хуку after_save, поменять данные в Redis.   Но вот непонятно, как из модели обратится к базе Redis.

```ruby
class User < ApplicationRecord

  after_save :refresh_bot

  def refresh_bot
    session = ActiveSupport::Cache.lookup_store(Rails.application.config.session_store)
    session.write(self.telegram_chat_id.to_s, self.lang)
  end
end
```

Этот код нерабочий, потому что Rails.application.config.session_store смотрит на другое хранилище:  ActionDispatch::Session::CookieStore:Class. Подскажите пожалуйста, как правильно обратится? Большое спасибо.

**Comment by printercu** [comment]
`YourTelegramController.session_store` - это уже готовый стор, нет необходимости в ActiveSupport::Cache.lookup_store.

Несколько советов, не относящихся к этому вопросу (можно игнорировать :) ):
- Разобраться в разнице методов класса и методах инстанса (можно погуглить "ruby instacnce methods vs class methods" или что-то подобное). 
- Понять ActiveSupport::Concern.
- Тогда станет понятным этот кусок: https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/session.rb#L11-L31 , и как из него получить ответ, который я дал в начале коментария.
- Использовать rubocop. Он может предотвратить возможные ошибки, и улучшить стиль написания (например, он посоветует не писать `self.`).
- Попробовать `show-method` в геме `pry`. Тут можно посмотреть `show-method session` в контроллере. Затем станет ясно, что надо смотреть `show-method self.class.build_session`. В нем будет видно метод `session_store` из ответа.
