### ISSUE TITLE
Few parameters for Callback queries 

### ISSUE THREAD

**Issue by boggddan** [telegram-bot-rb/telegram-bot#95]
Здравствуйте, Printercu. 
Не могли бы Вы подсказать, как сделать передаче нескольких параметров в Callback queries.
Я сделал через передачу json, который потом сериализируется в объект 

```ruby

def test
   ...
    obj = {farm_id: "#{farm_id}", activated: true}.to_json

    Telegram::Bot::Types::InlineKeyboardButton.new(url: '',text: 'test', callback_data: "farm_activated:#{obj}")
  end

  def farm_activated_callback_query(obj, *)
    params = JSON.parse(obj, symbolize_names: true)

    p params
    respond_with :message, text: params[:farm_id]
  end
```

Может, есть лучшее решение ? Спасибо.

П.С. И еще один маленький вопрос, при создании кнопки обязательно нужно задавать параметр `url` даже если он не используется `InlineKeyboardButton.new(url: '', ...)` , хотя судя по документации этот параметр не обязателен.

[inlinekeyboardmarkup](https://core.telegram.org/bots/api#inlinekeyboardmarkup)

> url | String | Optional. HTTP url to be opened when button is pressed

**Comment by printercu** [comment]
Здравствуйте!

1) думаю, это хорошее решение.
2) Ошибка со стороны телеграма или в методе `.new`? Если 1е, то значит их документация неверная или у них ошибка. Если 2е, то какая у вас версия гема telegram-bot-types?

**Comment by boggddan** [comment]
Спасибо.
telegram-bot-types (0.6.0)

Ошибка: 
```bash
Bad Request: Bad Request: can't parse inline keyboard button: Field "url" must be of type String
/coins/gems/gems/telegram-bot-0.14.0/lib/telegram/bot/client.rb:64:in `request'
/coins/gems/gems/telegram-bot-0.14.0/lib/telegram/bot/async.rb:156:in `request'
/coins/gems/gems/telegram-bot-0.14.0/lib/telegram/bot/client/api_helper.rb:22:in `block (2 levels) in define_helpers'
/coins/gems/gems/telegram-bot-0.14.0/lib/telegram/bot/updates_controller/reply_helpers.rb:13:in `public_send'
/coins/gems/gems/telegram-bot-0.14.0/lib/telegram/bot/updates_controller/reply_helpers.rb:13:in `respond_with'
/coins/gems/gems/telegram-bot-0.14.0/lib/telegram/bot/updates_controller/instrumentation.rb:40:in `block in respond_with'
/coins/gems/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
/coins/gems/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/coins/gems/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
/coins/gems/gems/telegram-bot-0.14.0/lib/telegram/bot/updates_controller/instrumentation.rb:15:in `instrument'
/coins/gems/gems/telegram-bot-0.14.0/lib/telegram/bot/updates_controller/instrumentation.rb:40:in `respond_with'
```

**Comment by printercu** [comment]
Попробуйте такой патч:
```ruby
Telegram::Bot::Types::Base.class_eval do
  def to_hash(*)
    super.reject { |_k, v| v.nil? }
  end
end
```
Если все ок, обновлю гем.

**Comment by printercu** [comment]
Если рельсы, то создать `config/initializers/telegram-bot-types_patch.rb`. Если не рельсы, то можно в том месте, где этот гем реквайрится.

**Comment by boggddan** [comment]
Спасибо, патч работает так как надо, и теперь кнопки можно создавать без параметра `url`

**Comment by boggddan** [comment]
Здравствуйте, а не подскажите, а когда сделаете обновление этого патча в боте? Спасибо.

**Comment by printercu** [comment]
Здравствуйте. Гем telegram-bot-types обновляется отдельно. Добавил сейчас релиз 0.6.1

**Comment by boggddan** [comment]
Спасибо, гем обновил! Все работает отлично!
