### ISSUE TITLE
Bad Request: BUTTON_URL_INVALID excluded from capture: No host specified, no public_key specified, no project_id specified

### ISSUE THREAD

**Issue by afuno** [telegram-bot-rb/telegram-bot#96]
```ruby
button = Telegram::Bot::Types::InlineKeyboardButton.new(
  text: t('telegram.general.buttons.look_on_the_site'),
  callback_data: "post_data:#{post.id}",
  url: public_post_url(post)
)

markup = Telegram::Bot::Types::InlineKeyboardMarkup.new(inline_keyboard: [[button]])
respond_with :message, text: t('telegram.general.messages.select_an_action'), reply_markup: markup.to_hash	
```

По факту кнопка не появляется, а в консоле появляется сообщение:

> Bad Request: Bad Request: BUTTON_URL_INVALID excluded from capture: No host specified, no public_key specified, no project_id specified

Сам по себе хэлпер `public_post_url` безобиден. Ошибка появляется только когда он оказывается у `url:`.

В `routes.rb` был добавлен этот код:

```ruby
Rails.application.routes.default_url_options =
  if Rails.env.production?
    { host: Settings.app.host, protocol: :https }
  else
    { host: Settings.app.host }
  end
```

В чем может быть проблема?

**Comment by printercu** [comment]
Обновите, пожалуйста, telegram-bot-types до последней версии, и проверьте воспроизводится ли там ошибка.

**Comment by printercu** [comment]
Попробуйте, пожалуйста, обновить telegram-bot-types до последней версии.
Если ошибка, сохраниться, попробуйте указывать урл "https://google.com/", например.

**Comment by printercu** [comment]
Еще я сомневаюсь, что можно указывать одновременно callback_data & url. Если ошибка сохраниться, попробуйте убрать callback_data.

**Comment by afuno** [comment]
@printercu удаление `callback_data` не помогло (хотя его здесь все же быть не должно). Но вот замена URL на `https://google.com/` - помогло.

Дальше я попробовал поиграться с URL и получил единственный рабочий вариант - работает ссылка на рабочий сайт с протоколом HTTPS. Все остальное - мимо.

**Comment by printercu** [comment]
С урлом public_post_url на внешнем домене тоже не работает? Может быть, ошибка для ссылок `http://localhost:3000/....`. Можно явно попробовать урлы указывать без хэлпера, посмотреть с каким проблема.

**Comment by printercu** [comment]
Вообще, ошибка из гема raven-ruby. Он у вас не настроен правильно, наверное.

А в коде ошибка, скорее всего, из-за того, что метод public_post_url не доступен в контроллере бота. Тут надо либо `Rails.application.routes.url_helpers.public_post_url` вызывать, либо инклудить `Rails.application.routes.url_helpers` в контроллер.

**Comment by afuno** [comment]
Да, Raven имеется на борту. Но он никогда ничего подобного не выдавал. Но я все равно проверю его.

Метод `public_post_url ` доступен. Он успешно генерирует нужную ссылку.

**Comment by printercu** [comment]
А, наверное, только эта часть к рэйвену относится: excluded from capture: No host specified, no public_key specified, no project_id specified

**Comment by printercu** [comment]
https://github.com/telegram-bot-rb/telegram-bot/issues/96#issuecomment-403286184 не помогло?

**Comment by afuno** [comment]
@printercu я если честно временно закастылил методом, в котором собираю ссылки без использования хелпера.
Попробую в ближайшее время еще покопаться.

**Comment by printercu** [comment]
Закрою. Если станет актуально, пишите - открою.
