### ISSUE TITLE
How I can use socks proxy?

### ISSUE THREAD

**Issue by s-anches** [telegram-bot-rb/telegram-bot#98]
Hi. Telegram API currently not working if I use http proxy. How I can set socks proxy to httpclient?
Currently httpclient not support socks proxy?

**Comment by printercu** [comment]
Hi! You can pass proxy setting via envar `HTTP_PROXY='http://myproxy:8080'` for all HTTPClient instances. There is other way: set `@client` for bot to `HTTPClient.new('http://myproxy:8080')`. This can be done with `instance_variable_set`.

You can also try this patch to pass proxy with config:
```ruby
# place this to config/initializers/telegram_bot_proxy.rb
Telegran::Bot::Client.prepend Module.new {
  def initialize(*, proxy: nil, **)
    super
    @client = HTTPClient.new(proxy) if proxy
  end
}
```

**Comment by printercu** [comment]
Some more details in #73

**Comment by s-anches** [comment]
As I understand HTTPClient don't support **socks** proxy? Telegram not working with http proxy.

**Comment by s-anches** [comment]
Now I fork httpclient and patch it with this pull request: https://github.com/nahi/httpclient/pull/380

**Comment by printercu** [comment]
I've missed it. Yes, it looks like it still does not support socks. All external requests goes through `Client#http_request`. You can override it to use any other http-client which supports socks.

**Comment by dapi** [comment]
here is an example that works for me:
```
# config/initializers/socks.rb
if Rails.env.development? && ENV['SOCKS_SERVER']
  require 'socksify' # add gem 'socksify'
  puts 'Initialize socks'
  TCPSocket::socks_server = ENV['SOCKS_SERVER']
  TCPSocket::socks_port = ENV['SOCKS_PORT']
  TCPSocket::socks_username = ENV['SOCKS_USERNAME']
  TCPSocket::socks_password = ENV['SOCKS_PASSWORD']
end
```

**Comment by dapi** [comment]
Can we close this issue?

**Comment by printercu** [comment]
Yes. Added this example to wiki.
